/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package OOPAssignment.Gui;

import OOPAssignment.model.Admin;

public class AdminLoginPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;
    private Admin admin;   // 之后用来验证登入

    public AdminLoginPanel(MainFrame mainFrame, Admin admin) {
        initComponents();
        this.mainFrame = mainFrame;
        this.admin = admin;
        //username press Enter Funtion
        usernameTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    passwordTf.requestFocus();
                }
            }
        });


        //Password press Enter Funtion
        passwordTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    loginBtnActionPerformed(null);
                }
            }
        });
    }

    // 下面这两个method,双击按钮后NetBeans会自动生成,你把内容填进去

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameTf = new javax.swing.JTextField();
        passwordTf = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(null);

        usernameTf.setBackground(new java.awt.Color(42, 42, 42));
        usernameTf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        usernameTf.setForeground(new java.awt.Color(204, 204, 204));
        usernameTf.setActionCommand("<Not Set>");
        usernameTf.setBorder(null);
        usernameTf.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usernameTf.addActionListener(this::usernameTfActionPerformed);
        add(usernameTf);
        usernameTf.setBounds(390, 195, 200, 20);

        passwordTf.setBackground(new java.awt.Color(42, 42, 42));
        passwordTf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        passwordTf.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        passwordTf.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        passwordTf.addActionListener(this::passwordTfActionPerformed);
        add(passwordTf);
        passwordTf.setBounds(390, 273, 200, 20);

        loginBtn.setContentAreaFilled(false);
        loginBtn.addActionListener(this::loginBtnActionPerformed);
        add(loginBtn);
        loginBtn.setBounds(340, 360, 80, 30);

        backBtn.setContentAreaFilled(false);
        backBtn.addActionListener(this::backBtnActionPerformed);
        add(backBtn);
        backBtn.setBounds(512, 360, 90, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOPAssignment/Gui/apulogo (1).png"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(0, 0, 110, 100);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOPAssignment/Gui/admin_login_dark_933x506 1.png"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(0, -6, 930, 510);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTfActionPerformed

    private void passwordTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTfActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        String inputUsername = usernameTf.getText();
        String inputPassword = new String(passwordTf.getPassword());  // JPasswordField要这样拿值

        boolean success = admin.login(inputUsername, inputPassword);

        if (success) {
            javax.swing.JOptionPane.showMessageDialog(this, "Login successful!");
            mainFrame.showPanel("admin");
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, "Wrong username or password!");
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        mainFrame.showPanel("menu");
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passwordTf;
    private javax.swing.JTextField usernameTf;
    // End of variables declaration//GEN-END:variables
}
