/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package OOPAssignment.Gui;

import OOPAssignment.model.Admin;
import java.awt.CardLayout;

/**
 *
 * @author Asus
 */
public class AdminPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;
    private Admin admin;
    private CardLayout innerCardLayout;
    
    public AdminPanel(MainFrame mainFrame, Admin admin) {
        initComponents();
        ManageStaffLbl.setVisible(false);
        this.mainFrame = mainFrame;
        this.admin = admin;

        innerCardLayout = new CardLayout();
        contentPanel.setLayout(innerCardLayout);
        contentPanel.add(new AdminDashboardPanel(admin), "dashboard");
        contentPanel.add(new ManageStaffPanel(admin), "manageStaff");
        contentPanel.add(new RosterPanel(admin), "roster");
        contentPanel.add(new ReportsPanel(admin), "reports");

        innerCardLayout.show(contentPanel, "dashboard");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jColorChooser2 = new javax.swing.JColorChooser();
        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        rosterBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        contentPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        reportBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        manageStaffBtn = new javax.swing.JButton();
        DashBoardLbl = new javax.swing.JLabel();
        ManageStaffLbl = new javax.swing.JLabel();
        RosterPanelLbl = new javax.swing.JLabel();
        ReportPanelLbl = new javax.swing.JLabel();
        dashboardBtn = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setText("jLabel1");

        jButton1.setText("jButton1");

        jPanel2.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLayout(null);

        rosterBtn.setContentAreaFilled(false);
        rosterBtn.addActionListener(this::rosterBtnActionPerformed);
        add(rosterBtn);
        rosterBtn.setBounds(20, 250, 140, 30);

        jPanel3.setLayout(new java.awt.CardLayout());
        add(jPanel3);
        jPanel3.setBounds(909, 514, 0, 0);

        contentPanel.setMaximumSize(new java.awt.Dimension(808, 500));

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        add(contentPanel);
        contentPanel.setBounds(167, 0, 770, 500);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOPAssignment/Gui/apulogo (1).png"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(30, 20, 110, 100);

        reportBtn.setContentAreaFilled(false);
        reportBtn.addActionListener(this::reportBtnActionPerformed);
        add(reportBtn);
        reportBtn.setBounds(20, 300, 130, 30);

        logoutBtn.setContentAreaFilled(false);
        logoutBtn.addActionListener(this::logoutBtnActionPerformed);
        add(logoutBtn);
        logoutBtn.setBounds(20, 440, 140, 40);

        manageStaffBtn.setContentAreaFilled(false);
        manageStaffBtn.addActionListener(this::manageStaffBtnActionPerformed);
        add(manageStaffBtn);
        manageStaffBtn.setBounds(20, 200, 140, 30);

        DashBoardLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOPAssignment/Gui/Admin Dashboard.png"))); // NOI18N
        add(DashBoardLbl);
        DashBoardLbl.setBounds(0, -10, 930, 510);

        ManageStaffLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOPAssignment/Gui/ManageStaff(1).png"))); // NOI18N
        add(ManageStaffLbl);
        ManageStaffLbl.setBounds(0, -10, 930, 510);

        RosterPanelLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOPAssignment/Gui/roster_schedule_clear 2.png"))); // NOI18N
        add(RosterPanelLbl);
        RosterPanelLbl.setBounds(0, -10, 930, 510);

        ReportPanelLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOPAssignment/Gui/generate_report_charts 1 (1).png"))); // NOI18N
        ReportPanelLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(ReportPanelLbl);
        ReportPanelLbl.setBounds(0, -10, 930, 510);

        dashboardBtn.setContentAreaFilled(false);
        dashboardBtn.addActionListener(this::dashboardBtnActionPerformed);
        add(dashboardBtn);
        dashboardBtn.setBounds(20, 140, 140, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void manageStaffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageStaffBtnActionPerformed
        innerCardLayout.show(contentPanel, "manageStaff");
        ManageStaffLbl.setVisible(true);
        DashBoardLbl.setVisible(false);
        RosterPanelLbl.setVisible(false);
        ReportPanelLbl.setVisible(false);
    }//GEN-LAST:event_manageStaffBtnActionPerformed

    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
        innerCardLayout.show(contentPanel, "dashboard");
        ManageStaffLbl.setVisible(false);
        DashBoardLbl.setVisible(true);
        RosterPanelLbl.setVisible(false);
        ReportPanelLbl.setVisible(false);
    }//GEN-LAST:event_dashboardBtnActionPerformed

    private void rosterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rosterBtnActionPerformed
        innerCardLayout.show(contentPanel, "roster");
        ManageStaffLbl.setVisible(false);
        DashBoardLbl.setVisible(false);
        RosterPanelLbl.setVisible(true);
        ReportPanelLbl.setVisible(false);
    }//GEN-LAST:event_rosterBtnActionPerformed

    private void reportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportBtnActionPerformed
        innerCardLayout.show(contentPanel, "reports");       
        ManageStaffLbl.setVisible(false);
        DashBoardLbl.setVisible(false);
        RosterPanelLbl.setVisible(false);
        ReportPanelLbl.setVisible(true);
    }//GEN-LAST:event_reportBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
            mainFrame.showPanel("menu");
    }//GEN-LAST:event_logoutBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DashBoardLbl;
    private javax.swing.JLabel ManageStaffLbl;
    private javax.swing.JLabel ReportPanelLbl;
    private javax.swing.JLabel RosterPanelLbl;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton dashboardBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton manageStaffBtn;
    private javax.swing.JButton reportBtn;
    private javax.swing.JButton rosterBtn;
    // End of variables declaration//GEN-END:variables
}
