/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package OOPAssignment.Gui;

import OOPAssignment.model.Appointment;
import OOPAssignment.model.Student;
import OOPAssignment.util.Validator;

public class BookAppointmentPanel extends javax.swing.JPanel {

    private Student student;

    public BookAppointmentPanel(Student student) {
        initComponents();
        this.student = student;

        javax.swing.SpinnerDateModel dateModel = new javax.swing.SpinnerDateModel();
        dateSpinner.setModel(dateModel);
        javax.swing.JSpinner.DateEditor dateEditor = new javax.swing.JSpinner.DateEditor(dateSpinner, "yyyy-MM-dd");
        dateSpinner.setEditor(dateEditor);

        resultArea.setEditable(false);
        refreshData();
    }

    private void refreshData() {
        java.util.List<Appointment> myAppointments = Appointment.findByStudent(student.getUsername());

        String result = "=== My Appointments ===\n";
        if (myAppointments.isEmpty()) {
            result += "No appointments yet.\n";
        } else {
            for (Appointment a : myAppointments) {
                result += a.getAppointmentId() + " - " + a.getDate() + " " + a.getTime()
                        + " with " + a.getCounselorUsername() + " (" + a.getStatus() + ")\n";
            }
        }
        resultArea.setText(result);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        counselorUsernameTf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        dateSpinner = new javax.swing.JSpinner();
        timeTf = new javax.swing.JTextField();
        typeCombo = new javax.swing.JComboBox<>();
        bookBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        refreshBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(counselorUsernameTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 107, 74, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Counselor Username:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 110, -1, -1));
        add(dateSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 160, 100, -1));
        add(timeTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 213, 74, -1));

        typeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Physical", "Online" }));
        add(typeCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 253, -1, -1));

        bookBtn.setBackground(new java.awt.Color(71, 102, 138));
        bookBtn.setForeground(new java.awt.Color(255, 255, 255));
        bookBtn.setText("Book");
        bookBtn.setBorder(null);
        bookBtn.addActionListener(this::bookBtnActionPerformed);
        add(bookBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 80, 20));

        resultArea.setBackground(new java.awt.Color(0, 0, 0));
        resultArea.setColumns(20);
        resultArea.setForeground(new java.awt.Color(255, 255, 255));
        resultArea.setRows(5);
        jScrollPane1.setViewportView(resultArea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 78, 460, 320));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Date:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 163, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Time:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 216, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Appointment type:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 256, -1, -1));

        refreshBtn.setBackground(new java.awt.Color(71, 102, 138));
        refreshBtn.setForeground(new java.awt.Color(255, 255, 255));
        refreshBtn.setText("Refresh");
        refreshBtn.setBorder(null);
        refreshBtn.addActionListener(this::refreshBtnActionPerformed);
        add(refreshBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 80, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOPAssignment/Gui/studentblank.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1150, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void bookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookBtnActionPerformed
        String counselorUsername = counselorUsernameTf.getText();

        java.util.Date selectedDate = (java.util.Date) dateSpinner.getValue();
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        String date = sdf.format(selectedDate);

        String time = timeTf.getText();
        String type = (String) typeCombo.getSelectedItem();

        if (Validator.isEmpty(counselorUsername) || Validator.isEmpty(time)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields!");
            return;
        }
        
        if (!Validator.isValidTime(time)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid time in HH:MM format (e.g. 09:00)!");
            return;
            }

        String id = Appointment.generateNextId();
        Appointment appointment = new Appointment(id, student.getUsername(), counselorUsername,
                date, time, type, "Pending");
        appointment.save();

        javax.swing.JOptionPane.showMessageDialog(this, "Appointment booked successfully! ID: " + id);
        counselorUsernameTf.setText("");
        timeTf.setText("");
        refreshData();
    }//GEN-LAST:event_bookBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
            refreshData();
    }//GEN-LAST:event_refreshBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookBtn;
    private javax.swing.JTextField counselorUsernameTf;
    private javax.swing.JSpinner dateSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JTextArea resultArea;
    private javax.swing.JTextField timeTf;
    private javax.swing.JComboBox<String> typeCombo;
    // End of variables declaration//GEN-END:variables
}
