/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package OOPAssignment.Gui;

import OOPAssignment.model.ConsultationRecord;
import OOPAssignment.model.User;
import OOPAssignment.util.Validator;
import java.util.List;

public class ConsultationRecordsPanel extends javax.swing.JPanel {

    private User counselor;

    public ConsultationRecordsPanel(User counselor) {
        initComponents();
        this.counselor = counselor;

        recordsArea.setEditable(false);
        refreshData();
    }

    private void refreshData() {
        List<ConsultationRecord> records = ConsultationRecord.findByCounselor(counselor.getUsername());

        String result = "=== My Consultation Records ===\n";
        if (records.isEmpty()) {
            result += "No records yet.\n";
        } else {
            for (ConsultationRecord r : records) {
                result += r.getDate() + " - Student: " + r.getStudentUsername()
                        + "\nNotes: " + r.getNotes()
                        + "\nRecommendation: " + r.getRecommendation() + "\n\n";
            }
        }
        recordsArea.setText(result);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentUsernameTf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        notesTa = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        recommendationTa = new javax.swing.JTextArea();
        saveRecordBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        recordsArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        setLayout(null);

        studentUsernameTf.setBorder(null);
        add(studentUsernameTf);
        studentUsernameTf.setBounds(40, 130, 260, 30);

        notesTa.setColumns(20);
        notesTa.setRows(5);
        jScrollPane1.setViewportView(notesTa);

        add(jScrollPane1);
        jScrollPane1.setBounds(40, 200, 260, 90);

        recommendationTa.setColumns(20);
        recommendationTa.setRows(5);
        jScrollPane2.setViewportView(recommendationTa);

        add(jScrollPane2);
        jScrollPane2.setBounds(40, 320, 260, 100);

        saveRecordBtn.setContentAreaFilled(false);
        saveRecordBtn.addActionListener(this::saveRecordBtnActionPerformed);
        add(saveRecordBtn);
        saveRecordBtn.setBounds(50, 450, 260, 40);

        recordsArea.setColumns(20);
        recordsArea.setRows(5);
        jScrollPane3.setViewportView(recordsArea);

        add(jScrollPane3);
        jScrollPane3.setBounds(350, 140, 350, 340);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOPAssignment/Gui/consultation_records_preview.png"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(-200, -10, 933, 520);
    }// </editor-fold>//GEN-END:initComponents

    private void saveRecordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveRecordBtnActionPerformed
        String studentUsername = studentUsernameTf.getText();
        String notes = notesTa.getText();
        String recommendation = recommendationTa.getText();

        if (Validator.isEmpty(studentUsername) || Validator.isEmpty(notes)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter student username and notes!");
            return;
        }

        String recordId = ConsultationRecord.generateNextId();
        String date = new java.text.SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date());

        ConsultationRecord record = new ConsultationRecord(recordId, studentUsername, counselor.getUsername(),
                date, notes, recommendation);
        record.save();

        javax.swing.JOptionPane.showMessageDialog(this, "Record saved successfully!");
        studentUsernameTf.setText("");
        notesTa.setText("");
        recommendationTa.setText("");
        refreshData();
    }//GEN-LAST:event_saveRecordBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea notesTa;
    private javax.swing.JTextArea recommendationTa;
    private javax.swing.JTextArea recordsArea;
    private javax.swing.JButton saveRecordBtn;
    private javax.swing.JTextField studentUsernameTf;
    // End of variables declaration//GEN-END:variables
}
