/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package OOPAssignment.Gui;

import OOPAssignment.model.Admin;
import OOPAssignment.model.User;
import OOPAssignment.model.Counselor;

public class CounselorLoginPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;
    private Admin admin;

    public CounselorLoginPanel(MainFrame mainFrame, Admin admin) {
        initComponents();
        this.mainFrame = mainFrame;
        this.admin = admin;

        UsernameTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    PasswordTF.requestFocus();
                }
            }
        });

        PasswordTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    LoginBTActionPerformed(null);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LoginBT = new javax.swing.JButton();
        BackBT = new javax.swing.JButton();
        UsernameTF = new javax.swing.JTextField();
        PasswordTF = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("Counselor Login");

        setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOPAssignment/Gui/apulogo (1).png"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(270, 20, 110, 100);

        LoginBT.setContentAreaFilled(false);
        LoginBT.addActionListener(this::LoginBTActionPerformed);
        add(LoginBT);
        LoginBT.setBounds(270, 340, 360, 40);

        BackBT.setContentAreaFilled(false);
        BackBT.addActionListener(this::BackBTActionPerformed);
        add(BackBT);
        BackBT.setBounds(270, 390, 360, 40);

        UsernameTF.setBackground(new java.awt.Color(51, 51, 51));
        UsernameTF.setBorder(null);
        UsernameTF.addActionListener(this::UsernameTFActionPerformed);
        add(UsernameTF);
        UsernameTF.setBounds(270, 210, 360, 40);

        PasswordTF.setBackground(new java.awt.Color(51, 51, 51));
        PasswordTF.setBorder(null);
        add(PasswordTF);
        PasswordTF.setBounds(270, 280, 360, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOPAssignment/Gui/counselorloginpanel.png"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(240, 0, 930, 510);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBTActionPerformed
    String inputUsername = UsernameTF.getText();
    String inputPassword = PasswordTF.getText();

    User foundStaff = admin.findStaffByUsername(inputUsername);

    if (foundStaff != null && foundStaff.login(inputUsername, inputPassword) 
            && foundStaff instanceof Counselor) {   // 加这个检查
        javax.swing.JOptionPane.showMessageDialog(this, "Login successful!");
        mainFrame.showCounselorPanel(foundStaff);
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Wrong username or password!");
    }
    }//GEN-LAST:event_LoginBTActionPerformed

    private void BackBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBTActionPerformed
        mainFrame.showPanel("menu");
    }//GEN-LAST:event_BackBTActionPerformed

    private void UsernameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBT;
    private javax.swing.JButton LoginBT;
    private javax.swing.JPasswordField PasswordTF;
    private javax.swing.JTextField UsernameTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
