/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package OOPAssignment.Gui;

import java.awt.CardLayout;
import javax.swing.JPanel;
import OOPAssignment.model.Admin; 

/**
 *
 * @author Asus
 */
public class MainFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    private final CardLayout cardLayout;
    private final JPanel cardPanel;
    private Admin sharedAdmin;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();

        sharedAdmin = new Admin("admin01", "adminpass", "Ali");

        cardLayout = new CardLayout();
        cardPanel = new JPanel(cardLayout);

        cardPanel.add(new MenuPanel(this), "menu");
        cardPanel.add(new AdminLoginPanel(this, sharedAdmin), "adminLogin");
        cardPanel.add(new AdminPanel(this, sharedAdmin), "admin");
        cardPanel.add(new StudentLoginPanel(this), "studentLogin");
        cardPanel.add(new CounselorLoginPanel(this, sharedAdmin), "counselorLogin");
        cardPanel.add(new ReceptionistLoginPanel(this, sharedAdmin), "receptionistLogin");   // 改成这行,加ReceptionistLoginPanel

        getContentPane().removeAll();
        getContentPane().setLayout(new java.awt.BorderLayout());
        getContentPane().add(cardPanel, java.awt.BorderLayout.CENTER);

        setSize(933, 539);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        cardLayout.show(cardPanel, "menu");
        revalidate();
        repaint();
    }

    public void showPanel(String name) {
        cardLayout.show(cardPanel, name);
    }
    
    public void showStudentPanel(OOPAssignment.model.Student loggedInStudent) {
        cardPanel.add(new StudentPanel(this, sharedAdmin, loggedInStudent), "student");
        cardLayout.show(cardPanel, "student");
    }
    public void showCounselorPanel(OOPAssignment.model.User loggedInCounselor) {
        cardPanel.add(new CounselorPanel(this, sharedAdmin, loggedInCounselor), "counselor");
        cardLayout.show(cardPanel, "counselor");
    }
    
    public void showReceptionistPanel(OOPAssignment.model.User loggedInReceptionist) {
        cardPanel.add(new ReceptionistPanel(this, sharedAdmin, loggedInReceptionist), "receptionist");
        cardLayout.show(cardPanel, "receptionist");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 933, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
