/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package OOPAssignment.Gui;

import java.awt.CardLayout;
import javax.swing.JPanel;
import OOPAssignment.model.Admin; 

/**
 *
 * @author Asus
 */
public class MainFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    private final CardLayout cardLayout;
    private final JPanel cardPanel;
    private Admin sharedAdmin;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        sharedAdmin = new Admin("admin01", "adminpass", "Ali");

        cardLayout = new CardLayout();
        cardPanel = new JPanel(cardLayout);

        cardPanel.add(new MenuPanel(this), "menu");
        cardPanel.add(new AdminLoginPanel(this, sharedAdmin), "adminLogin");   // ✅ 补上sharedAdmin
        cardPanel.add(new AdminPanel(this, sharedAdmin), "admin");
        // 之后Bosco/Bryan/Eeonn写好自己的panel,也一样加进来
        cardPanel.add(new CounselorLoginPanel(), "counselor");
        // cardPanel.add(new ReceptionistPanel(), "receptionist");
        // cardPanel.add(new StudentPanel(), "student");

        getContentPane().removeAll();          // 清掉GroupLayout留下的空设置
        getContentPane().setLayout(new java.awt.BorderLayout());  // 换成简单的Layout
        getContentPane().add(cardPanel, java.awt.BorderLayout.CENTER);

        setSize(933, 506);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        cardLayout.show(cardPanel, "menu");
        revalidate();
        repaint();
    }

    public void showPanel(String name) {
        cardLayout.show(cardPanel, name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 933, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
