/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package OOPAssignment.Gui;
import OOPAssignment.model.Admin;
import OOPAssignment.util.Validator;
/**
 *
 * @author Asus
 */
public class ManageStaffPanel extends javax.swing.JPanel {

    private Admin admin;

    public ManageStaffPanel(Admin admin) {
        initComponents();
        this.admin = admin;
        refreshData();
    }
        private void refreshData() {
            staffListArea.setText(admin.viewAllStaff());
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameLabel = new javax.swing.JLabel();
        usernameTf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        passwordTf = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        nameTf = new javax.swing.JTextField();
        addStaffBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        staffListArea = new javax.swing.JTextArea();
        deleteStaffBtn = new javax.swing.JButton();
        updateStaffBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();

        usernameLabel.setText("Username: ");

        usernameTf.addActionListener(this::usernameTfActionPerformed);

        jLabel1.setText("Password:");

        passwordTf.addActionListener(this::passwordTfActionPerformed);

        jLabel2.setText("Name    :");

        nameTf.addActionListener(this::nameTfActionPerformed);

        addStaffBtn.setText("Add Staff");
        addStaffBtn.addActionListener(this::addStaffBtnActionPerformed);

        staffListArea.setColumns(20);
        staffListArea.setRows(5);
        jScrollPane1.setViewportView(staffListArea);

        deleteStaffBtn.setText("Delete");
        deleteStaffBtn.addActionListener(this::deleteStaffBtnActionPerformed);

        updateStaffBtn.setText("Update");
        updateStaffBtn.addActionListener(this::updateStaffBtnActionPerformed);

        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(this::refreshBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(passwordTf, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(usernameLabel)
                                .addGap(50, 50, 50)
                                .addComponent(usernameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(addStaffBtn)
                        .addGap(33, 33, 33)
                        .addComponent(updateStaffBtn)
                        .addGap(18, 18, 18)
                        .addComponent(deleteStaffBtn)
                        .addGap(121, 121, 121)
                        .addComponent(refreshBtn)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(usernameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(passwordTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStaffBtn)
                    .addComponent(deleteStaffBtn)
                    .addComponent(updateStaffBtn)
                    .addComponent(refreshBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void passwordTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTfActionPerformed

    }//GEN-LAST:event_passwordTfActionPerformed

    private void addStaffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStaffBtnActionPerformed
        String username = usernameTf.getText();
        String password = passwordTf.getText();
        String name = nameTf.getText();

        if (OOPAssignment.util.Validator.isEmpty(username) ||
            OOPAssignment.util.Validator.isEmpty(password) ||
            OOPAssignment.util.Validator.isEmpty(name)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields!");
            return;
        }

        if (!OOPAssignment.util.Validator.isValidPassword(password)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Password must be at least 6 characters!");
            return;
        }

        if (admin.isUsernameTaken(username)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Username already exists! Please choose another.");
            return;
        }

        OOPAssignment.model.Counselor newStaff = new OOPAssignment.model.Counselor(username, password, name);
        boolean success = admin.addStaff(newStaff);

        if (success) {
            javax.swing.JOptionPane.showMessageDialog(this, "Staff added successfully!");
            usernameTf.setText("");
            passwordTf.setText("");
            nameTf.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Failed to add staff!");
        }
    }//GEN-LAST:event_addStaffBtnActionPerformed

    private void usernameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTfActionPerformed

    private void nameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTfActionPerformed

    private void deleteStaffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStaffBtnActionPerformed
            String username = usernameTf.getText();

            if (Validator.isEmpty(username)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please enter username to delete!");
                return;
            }

            int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to delete this staff?", 
                "Confirm Delete", 
                javax.swing.JOptionPane.YES_NO_OPTION);

            if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                boolean success = admin.deleteStaff(username);

                if (success) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Staff deleted successfully!");
                    usernameTf.setText("");
                    passwordTf.setText("");
                    nameTf.setText("");
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Staff not found!");
                }
            }

    }//GEN-LAST:event_deleteStaffBtnActionPerformed

    private void updateStaffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStaffBtnActionPerformed
            String username = usernameTf.getText();
            String newName = nameTf.getText();

            if (Validator.isEmpty(username) || Validator.isEmpty(newName)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please enter username and new name!");
                return;
            }

            boolean success = admin.updateStaff(username, newName);

            if (success) {
                javax.swing.JOptionPane.showMessageDialog(this, "Staff updated successfully!");
                usernameTf.setText("");
                passwordTf.setText("");
                nameTf.setText("");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Staff not found!");
        }
    }//GEN-LAST:event_updateStaffBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        refreshData();
    }//GEN-LAST:event_refreshBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStaffBtn;
    private javax.swing.JButton deleteStaffBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTf;
    private javax.swing.JPasswordField passwordTf;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JTextArea staffListArea;
    private javax.swing.JButton updateStaffBtn;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTf;
    // End of variables declaration//GEN-END:variables
}
