/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package OOPAssignment.Gui;

import OOPAssignment.model.Admin;
import OOPAssignment.model.Appointment;
import OOPAssignment.util.Validator;
import java.util.List;

public class ManageAppointmentPanel extends javax.swing.JPanel {

    private Admin admin;

    public ManageAppointmentPanel(Admin admin) {
        initComponents();
        this.admin = admin;

        javax.swing.SpinnerDateModel dateModel = new javax.swing.SpinnerDateModel();
        dateSpinner.setModel(dateModel);
        javax.swing.JSpinner.DateEditor dateEditor = new javax.swing.JSpinner.DateEditor(dateSpinner, "yyyy-MM-dd");
        dateSpinner.setEditor(dateEditor);

        appointmentListArea.setEditable(false);
        refreshData();
    }

    private void refreshData() {
        List<Appointment> all = Appointment.loadAll();

        String result = "=== All Appointments ===\n";
        if (all.isEmpty()) {
            result += "No appointments yet.\n";
        } else {
            for (Appointment a : all) {
                result += a.getAppointmentId() + " - Student: " + a.getStudentUsername()
                        + " - Counselor: " + a.getCounselorUsername()
                        + " - " + a.getDate() + " " + a.getTime()
                        + " - Type: " + a.getType()
                        + " (" + a.getStatus() + ")\n";
            }
        }
        appointmentListArea.setText(result);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        counselorUsernameTf = new javax.swing.JTextField();
        timeTf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dateSpinner = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        typeCombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        confirmBtn = new javax.swing.JButton();
        appointmentIdTf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        assignCounselorBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        appointmentListArea = new javax.swing.JTextArea();
        updateBtn = new javax.swing.JButton();

        jLabel2.setText("Counselor Username: ");

        jLabel3.setText("Date: ");

        jLabel4.setText("Time");

        typeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Physical", "Online" }));
        typeCombo.addActionListener(this::typeComboActionPerformed);

        jLabel5.setText("Appointment Type");

        confirmBtn.setText("Comfired");
        confirmBtn.addActionListener(this::confirmBtnActionPerformed);

        jLabel6.setText("Appointment ID");

        assignCounselorBtn.setText("Assign Counselor");
        assignCounselorBtn.addActionListener(this::assignCounselorBtnActionPerformed);

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(this::cancelBtnActionPerformed);

        appointmentListArea.setEditable(false);
        appointmentListArea.setColumns(20);
        appointmentListArea.setRows(5);
        jScrollPane1.setViewportView(appointmentListArea);

        updateBtn.setText("Update");
        updateBtn.addActionListener(this::updateBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(counselorUsernameTf)
                                    .addComponent(dateSpinner)
                                    .addComponent(timeTf)
                                    .addComponent(typeCombo, 0, 102, Short.MAX_VALUE)))
                            .addComponent(jLabel5)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(appointmentIdTf, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(confirmBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateBtn)
                        .addGap(15, 15, 15)
                        .addComponent(cancelBtn)
                        .addGap(18, 18, 18)
                        .addComponent(assignCounselorBtn)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(appointmentIdTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(counselorUsernameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(dateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(timeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(typeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmBtn)
                    .addComponent(updateBtn)
                    .addComponent(cancelBtn)
                    .addComponent(assignCounselorBtn))
                .addContainerGap(79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void assignCounselorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignCounselorBtnActionPerformed
        String appointmentId = appointmentIdTf.getText();
        String newCounselorUsername = counselorUsernameTf.getText();

        if (Validator.isEmpty(appointmentId) || Validator.isEmpty(newCounselorUsername)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter appointment ID and counselor username!");
            return;
        }

        Appointment appointment = Appointment.findById(appointmentId);
        if (appointment == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Appointment not found!");
            return;
        }

        appointment.setCounselorUsername(newCounselorUsername);
        appointment.save();

        javax.swing.JOptionPane.showMessageDialog(this, "Counselor assigned successfully!");
        refreshData();
    }//GEN-LAST:event_assignCounselorBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        String appointmentId = appointmentIdTf.getText();

        if (Validator.isEmpty(appointmentId)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter appointment ID to cancel!");
            return;
        }

        boolean success = Appointment.cancelById(appointmentId);

        if (success) {
            javax.swing.JOptionPane.showMessageDialog(this, "Appointment cancelled successfully!");
            appointmentIdTf.setText("");
            refreshData();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Appointment not found!");
        }
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void typeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeComboActionPerformed

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        String appointmentId = appointmentIdTf.getText();

        if (Validator.isEmpty(appointmentId)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter appointment ID to confirm!");
            return;
        }

        Appointment appointment = Appointment.findById(appointmentId);
        if (appointment == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Appointment not found!");
            return;
        }

        appointment.setStatus("Confirmed");
        appointment.save();

        javax.swing.JOptionPane.showMessageDialog(this, "Appointment confirmed successfully!");
        appointmentIdTf.setText("");
        refreshData();
    }//GEN-LAST:event_confirmBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        String appointmentId = appointmentIdTf.getText();

        if (Validator.isEmpty(appointmentId)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter appointment ID to update!");
            return;
        }

        Appointment appointment = Appointment.findById(appointmentId);
        if (appointment == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Appointment not found!");
            return;
        }

        java.util.Date selectedDate = (java.util.Date) dateSpinner.getValue();
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        String newDate = sdf.format(selectedDate);

        String newTime = timeTf.getText();
        String newType = (String) typeCombo.getSelectedItem();

        if (!newDate.equals(appointment.getDate())) {
            appointment.setDate(newDate);
        }
        if (!Validator.isEmpty(newTime)) {
            appointment.setTime(newTime);
        }
        appointment.setType(newType);

        appointment.save();

        javax.swing.JOptionPane.showMessageDialog(this, "Appointment updated successfully!");
        appointmentIdTf.setText("");
        timeTf.setText("");
        refreshData();
    }//GEN-LAST:event_updateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField appointmentIdTf;
    private javax.swing.JTextArea appointmentListArea;
    private javax.swing.JButton assignCounselorBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JTextField counselorUsernameTf;
    private javax.swing.JSpinner dateSpinner;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField timeTf;
    private javax.swing.JComboBox<String> typeCombo;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
