/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package OOPAssignment.Gui;
import OOPAssignment.model.Admin;
import OOPAssignment.util.Validator;
/**
 *
 * @author Asus
 */
public class ManageStaffPanel extends javax.swing.JPanel {

    private Admin admin;

    public ManageStaffPanel(Admin admin) {
        initComponents();
        this.admin = admin;
        refreshData();
    }
        private void refreshData() {
            staffListArea.setText(admin.viewAllStaff());
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameTf = new javax.swing.JTextField();
        passwordTf = new javax.swing.JPasswordField();
        nameTf = new javax.swing.JTextField();
        addStaffBtn = new javax.swing.JButton();
        deleteStaffBtn = new javax.swing.JButton();
        updateStaffBtn = new javax.swing.JButton();
        roleCombo = new javax.swing.JComboBox<>();
        loadStaffBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        staffListArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        setLayout(null);

        usernameTf.setBackground(new java.awt.Color(45, 45, 50));
        usernameTf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        usernameTf.setForeground(new java.awt.Color(204, 204, 204));
        usernameTf.setBorder(null);
        usernameTf.addActionListener(this::usernameTfActionPerformed);
        add(usernameTf);
        usernameTf.setBounds(50, 112, 170, 30);

        passwordTf.setBackground(new java.awt.Color(45, 45, 50));
        passwordTf.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        passwordTf.setBorder(null);
        passwordTf.addActionListener(this::passwordTfActionPerformed);
        add(passwordTf);
        passwordTf.setBounds(320, 210, 220, 20);

        nameTf.setBackground(new java.awt.Color(45, 45, 50));
        nameTf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nameTf.setForeground(new java.awt.Color(204, 204, 204));
        nameTf.setBorder(null);
        nameTf.addActionListener(this::nameTfActionPerformed);
        add(nameTf);
        nameTf.setBounds(60, 210, 220, 25);

        addStaffBtn.setContentAreaFilled(false);
        addStaffBtn.addActionListener(this::addStaffBtnActionPerformed);
        add(addStaffBtn);
        addStaffBtn.setBounds(359, 283, 110, 30);

        deleteStaffBtn.setBorderPainted(false);
        deleteStaffBtn.setContentAreaFilled(false);
        deleteStaffBtn.addActionListener(this::deleteStaffBtnActionPerformed);
        add(deleteStaffBtn);
        deleteStaffBtn.setBounds(600, 283, 90, 30);

        updateStaffBtn.setContentAreaFilled(false);
        updateStaffBtn.addActionListener(this::updateStaffBtnActionPerformed);
        add(updateStaffBtn);
        updateStaffBtn.setBounds(490, 280, 90, 30);

        roleCombo.setBackground(new java.awt.Color(45, 45, 50));
        roleCombo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        roleCombo.setForeground(new java.awt.Color(204, 204, 204));
        roleCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Counselor", "Receptionist" }));
        roleCombo.setBorder(null);
        add(roleCombo);
        roleCombo.setBounds(50, 270, 150, 40);

        loadStaffBtn.setContentAreaFilled(false);
        loadStaffBtn.addActionListener(this::loadStaffBtnActionPerformed);
        add(loadStaffBtn);
        loadStaffBtn.setBounds(230, 113, 100, 30);

        staffListArea.setEditable(false);
        staffListArea.setBackground(new java.awt.Color(20, 20, 22));
        staffListArea.setColumns(20);
        staffListArea.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        staffListArea.setForeground(new java.awt.Color(204, 204, 204));
        staffListArea.setRows(5);
        staffListArea.setText("dwadsdaw");
        staffListArea.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        staffListArea.setFocusTraversalPolicyProvider(true);
        staffListArea.setFocusable(false);
        staffListArea.setSelectionColor(new java.awt.Color(20, 20, 22));
        jScrollPane1.setViewportView(staffListArea);

        add(jScrollPane1);
        jScrollPane1.setBounds(28, 350, 720, 133);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOPAssignment/Gui/ManageStaff(1).png"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(932, 507));
        jLabel3.setMinimumSize(new java.awt.Dimension(932, 507));
        add(jLabel3);
        jLabel3.setBounds(-170, 0, 940, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void passwordTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTfActionPerformed

    }//GEN-LAST:event_passwordTfActionPerformed

    private void addStaffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStaffBtnActionPerformed
        String username = usernameTf.getText();
        String password = passwordTf.getText();
        String name = nameTf.getText();
        String role = (String) roleCombo.getSelectedItem();

        if (Validator.isEmpty(username) || Validator.isEmpty(password) || Validator.isEmpty(name)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields!");
            return;
        }

        if (!Validator.isValidPassword(password)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Password must be at least 6 characters!");
            return;
        }

        if (admin.isUsernameTaken(username)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Username already exists! Please choose another.");
            return;
        }

        OOPAssignment.model.User newStaff;
        if (role.equals("Receptionist")) {
            newStaff = new OOPAssignment.model.Receptionist(username, password, name);
        } else {
            newStaff = new OOPAssignment.model.Counselor(username, password, name);
        }

        boolean success = admin.addStaff(newStaff);

        if (success) {
            javax.swing.JOptionPane.showMessageDialog(this, "Staff added successfully!");
            usernameTf.setText("");
            passwordTf.setText("");
            nameTf.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Failed to add staff!");
        }
        refreshData();
    }//GEN-LAST:event_addStaffBtnActionPerformed

    private void usernameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTfActionPerformed

    private void nameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTfActionPerformed

    private void deleteStaffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStaffBtnActionPerformed
            String username = usernameTf.getText();

            if (Validator.isEmpty(username)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please enter username to delete!");
                return;
            }

            int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to delete this staff?", 
                "Confirm Delete", 
                javax.swing.JOptionPane.YES_NO_OPTION);

            if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                boolean success = admin.deleteStaff(username);

                if (success) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Staff deleted successfully!");
                    usernameTf.setText("");
                    passwordTf.setText("");
                    nameTf.setText("");
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Staff not found!");
                }
            }
        refreshData();
    }//GEN-LAST:event_deleteStaffBtnActionPerformed

    private void updateStaffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStaffBtnActionPerformed
            String username = usernameTf.getText();
            String newName = nameTf.getText();

            if (Validator.isEmpty(username) || Validator.isEmpty(newName)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please enter username and new name!");
                return;
            }

            boolean success = admin.updateStaff(username, newName);

            if (success) {
                javax.swing.JOptionPane.showMessageDialog(this, "Staff updated successfully!");
                usernameTf.setText("");
                passwordTf.setText("");
                nameTf.setText("");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Staff not found!");
        }
        refreshData();
    }//GEN-LAST:event_updateStaffBtnActionPerformed

    private void loadStaffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadStaffBtnActionPerformed
            String username = usernameTf.getText();

    if (Validator.isEmpty(username)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter username to search!");
        return;
    }

    OOPAssignment.model.User foundStaff = admin.findStaffByUsername(username);

    if (foundStaff != null) {
        nameTf.setText(foundStaff.getName());
        javax.swing.JOptionPane.showMessageDialog(this, "Staff found! You can now edit the name and click Update.");
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Staff not found!");
    }
    }//GEN-LAST:event_loadStaffBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStaffBtn;
    private javax.swing.JButton deleteStaffBtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadStaffBtn;
    private javax.swing.JTextField nameTf;
    private javax.swing.JPasswordField passwordTf;
    private javax.swing.JComboBox<String> roleCombo;
    private javax.swing.JTextArea staffListArea;
    private javax.swing.JButton updateStaffBtn;
    private javax.swing.JTextField usernameTf;
    // End of variables declaration//GEN-END:variables
}
