/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package OOPAssignment.Gui;

public class ManageStudentPanel extends javax.swing.JPanel {

    public ManageStudentPanel() {
        initComponents();

        studentListArea.setEditable(false);
        refreshData();

        // Student ID → Enter跳去Name
        studentIdTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    nameTf.requestFocus();
                }
            }
        });

        // Name → Enter跳去Username
        nameTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    usernameTf.requestFocus();
                }
            }
        });

        // Username → Enter跳去Password
        usernameTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    passwordTf.requestFocus();
                }
            }
        });

        // Password → Enter跳去Email
        passwordTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    emailTf.requestFocus();
                }
            }
        });

        // Email → Enter直接送出
        emailTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    addStudentBtnActionPerformed(null);
                }
            }
        });
    }

    private void refreshData() {
        java.util.List<OOPAssignment.model.Student> students = OOPAssignment.model.Student.loadAll();

        String result = "=== Student List ===\n";
        if (students.isEmpty()) {
            result += "No students yet.\n";
        } else {
            for (OOPAssignment.model.Student s : students) {
                result += s.getStudentId() + " - " + s.getName() + " (" + s.getUsername() + ") - " + s.getEmail() + "\n";
            }
        }
        studentListArea.setText(result);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentIdTf = new javax.swing.JTextField();
        nameTf = new javax.swing.JTextField();
        passwordTf = new javax.swing.JTextField();
        emailTf = new javax.swing.JTextField();
        addStudentBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentListArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        usernameTf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        loadStudentBtn = new javax.swing.JButton();
        updateStudentBtn = new javax.swing.JButton();
        deleteStudentBtn = new javax.swing.JButton();

        studentIdTf.addActionListener(this::studentIdTfActionPerformed);

        emailTf.addActionListener(this::emailTfActionPerformed);

        addStudentBtn.setText("Add Student");
        addStudentBtn.addActionListener(this::addStudentBtnActionPerformed);

        studentListArea.setEditable(false);
        studentListArea.setColumns(20);
        studentListArea.setRows(5);
        jScrollPane1.setViewportView(studentListArea);

        jLabel1.setText("Student ID");

        jLabel2.setText("username");

        jLabel4.setText("Name");

        jLabel5.setText("password");

        jLabel3.setText("Email");

        loadStudentBtn.setText("Load Student Info");
        loadStudentBtn.addActionListener(this::loadStudentBtnActionPerformed);

        updateStudentBtn.setText("Update Student");
        updateStudentBtn.addActionListener(this::updateStudentBtnActionPerformed);

        deleteStudentBtn.setText("Delete");
        deleteStudentBtn.addActionListener(this::deleteStudentBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5))
                            .addComponent(jLabel1))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(emailTf, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                .addComponent(passwordTf)
                                .addComponent(nameTf)
                                .addComponent(studentIdTf))
                            .addComponent(usernameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addStudentBtn)
                            .addComponent(updateStudentBtn))
                        .addGap(6, 6, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loadStudentBtn)
                            .addComponent(deleteStudentBtn))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studentIdTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(usernameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(passwordTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(emailTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addStudentBtn)
                            .addComponent(deleteStudentBtn))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadStudentBtn)
                    .addComponent(updateStudentBtn))
                .addGap(89, 89, 89))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void studentIdTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIdTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIdTfActionPerformed

    private void addStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentBtnActionPerformed
    String name = nameTf.getText();
    String username = usernameTf.getText();
    String password = passwordTf.getText();
    String email = emailTf.getText();

    if (OOPAssignment.util.Validator.isEmpty(name)
            || OOPAssignment.util.Validator.isEmpty(username)
            || OOPAssignment.util.Validator.isEmpty(password)
            || OOPAssignment.util.Validator.isEmpty(email)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields!");
        return;
    }

    if (OOPAssignment.model.Student.findByUsername(username) != null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Username already exists!");
        return;
    }

    String studentId = OOPAssignment.model.Student.generateNextId();   // 自动生成,用户完全不用管

    OOPAssignment.model.Student newStudent = new OOPAssignment.model.Student(studentId, name, username, password, email);
    newStudent.save();

    javax.swing.JOptionPane.showMessageDialog(this, "Student added successfully! ID: " + studentId);
    nameTf.setText("");
    usernameTf.setText("");
    passwordTf.setText("");
    emailTf.setText("");
    refreshData();
    }//GEN-LAST:event_addStudentBtnActionPerformed

    private void emailTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTfActionPerformed

    private void loadStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadStudentBtnActionPerformed
    String studentId = studentIdTf.getText();

    if (OOPAssignment.util.Validator.isEmpty(studentId)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter Student ID to search!");
        return;
    }

    OOPAssignment.model.Student foundStudent = OOPAssignment.model.Student.findByStudentId(studentId);

    if (foundStudent != null) {
        usernameTf.setText(foundStudent.getUsername());
        nameTf.setText(foundStudent.getName());
        emailTf.setText(foundStudent.getEmail());
        javax.swing.JOptionPane.showMessageDialog(this, "Student found! You can now edit and click Update.");
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Student not found!");
    }
    }//GEN-LAST:event_loadStudentBtnActionPerformed

    private void updateStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStudentBtnActionPerformed
    String studentId = studentIdTf.getText();

    if (OOPAssignment.util.Validator.isEmpty(studentId)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter Student ID to update!");
        return;
    }

    OOPAssignment.model.Student existingStudent = OOPAssignment.model.Student.findByStudentId(studentId);

    if (existingStudent == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Student not found!");
        return;
    }

    String newName = nameTf.getText();
    String newEmail = emailTf.getText();

    if (!OOPAssignment.util.Validator.isEmpty(newName)) {
        existingStudent.setName(newName);
    }
    if (!OOPAssignment.util.Validator.isEmpty(newEmail)) {
        existingStudent.setEmail(newEmail);
    }

    existingStudent.save();

    javax.swing.JOptionPane.showMessageDialog(this, "Student updated successfully!");
    studentIdTf.setText("");
    nameTf.setText("");
    usernameTf.setText("");
    passwordTf.setText("");
    emailTf.setText("");
    refreshData();
    }//GEN-LAST:event_updateStudentBtnActionPerformed

    private void deleteStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStudentBtnActionPerformed
    String studentId = studentIdTf.getText();

    if (OOPAssignment.util.Validator.isEmpty(studentId)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter Student ID to delete!");
        return;
    }

    int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
        "Are you sure you want to delete this student?",
        "Confirm Delete",
        javax.swing.JOptionPane.YES_NO_OPTION);

    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        boolean success = OOPAssignment.model.Student.deleteByStudentId(studentId);

        if (success) {
            javax.swing.JOptionPane.showMessageDialog(this, "Student deleted successfully!");
            studentIdTf.setText("");
            nameTf.setText("");
            usernameTf.setText("");
            passwordTf.setText("");
            emailTf.setText("");
            refreshData();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Student not found!");
        }
    }
    }//GEN-LAST:event_deleteStudentBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStudentBtn;
    private javax.swing.JButton deleteStudentBtn;
    private javax.swing.JTextField emailTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadStudentBtn;
    private javax.swing.JTextField nameTf;
    private javax.swing.JTextField passwordTf;
    private javax.swing.JTextField studentIdTf;
    private javax.swing.JTextArea studentListArea;
    private javax.swing.JButton updateStudentBtn;
    private javax.swing.JTextField usernameTf;
    // End of variables declaration//GEN-END:variables
}
