/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package OOPAssignment.Gui;

import OOPAssignment.model.Admin;
import OOPAssignment.model.Appointment;
import OOPAssignment.util.Validator;
import java.util.List;

public class ManageAppointmentPanel extends javax.swing.JPanel {

    private Admin admin;

    public ManageAppointmentPanel(Admin admin) {
        initComponents();
        this.admin = admin;

        javax.swing.SpinnerDateModel dateModel = new javax.swing.SpinnerDateModel();
        dateSpinner.setModel(dateModel);
        javax.swing.JSpinner.DateEditor dateEditor = new javax.swing.JSpinner.DateEditor(dateSpinner, "yyyy-MM-dd");
        dateSpinner.setEditor(dateEditor);

        appointmentListArea.setEditable(false);
        refreshData();
    }

    private void refreshData() {
        List<Appointment> all = Appointment.loadAll();

        String result = "";
        if (all.isEmpty()) {
            result += "No appointments yet.\n";
        } else {
            for (Appointment a : all) {
                result += a.getAppointmentId() + " - Student: " + a.getStudentUsername()
                        + " - Counselor: " + a.getCounselorUsername()
                        + " - " + a.getDate() + " " + a.getTime()
                        + " - Type: " + a.getType()
                        + " (" + a.getStatus() + ")\n";
            }
        }
        appointmentListArea.setText(result);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentUsernameTf = new javax.swing.JTextField();
        timeTf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dateSpinner = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        typeCombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        confirmBtn = new javax.swing.JButton();
        appointmentIdTf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        assignCounselorBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        appointmentListArea = new javax.swing.JTextArea();
        updateBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        counselorUsernameTf1 = new javax.swing.JTextField();
        createBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        studentUsernameTf.addActionListener(this::studentUsernameTfActionPerformed);
        add(studentUsernameTf);
        studentUsernameTf.setBounds(140, 113, 102, 30);
        add(timeTf);
        timeTf.setBounds(80, 240, 102, 30);

        jLabel2.setText("Student Username ");
        add(jLabel2);
        jLabel2.setBounds(20, 120, 100, 16);
        add(dateSpinner);
        dateSpinner.setBounds(80, 200, 102, 30);

        jLabel3.setText("Date: ");
        add(jLabel3);
        jLabel3.setBounds(20, 210, 50, 16);

        jLabel4.setText("Time");
        add(jLabel4);
        jLabel4.setBounds(20, 250, 50, 16);

        typeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Physical", "Online" }));
        typeCombo.addActionListener(this::typeComboActionPerformed);
        add(typeCombo);
        typeCombo.setBounds(140, 283, 102, 30);

        jLabel5.setText("Appointment Type");
        add(jLabel5);
        jLabel5.setBounds(20, 290, 100, 16);

        confirmBtn.setContentAreaFilled(false);
        confirmBtn.addActionListener(this::confirmBtnActionPerformed);
        add(confirmBtn);
        confirmBtn.setBounds(310, 370, 150, 40);
        add(appointmentIdTf);
        appointmentIdTf.setBounds(120, 60, 102, 30);

        jLabel6.setText("Appointment ID");
        add(jLabel6);
        jLabel6.setBounds(20, 70, 85, 16);

        assignCounselorBtn.setContentAreaFilled(false);
        assignCounselorBtn.addActionListener(this::assignCounselorBtnActionPerformed);
        add(assignCounselorBtn);
        assignCounselorBtn.setBounds(310, 440, 220, 50);

        cancelBtn.setContentAreaFilled(false);
        cancelBtn.addActionListener(this::cancelBtnActionPerformed);
        add(cancelBtn);
        cancelBtn.setBounds(490, 370, 100, 40);

        appointmentListArea.setEditable(false);
        appointmentListArea.setColumns(20);
        appointmentListArea.setRows(5);
        jScrollPane1.setViewportView(appointmentListArea);

        add(jScrollPane1);
        jScrollPane1.setBounds(310, 30, 380, 230);

        updateBtn.setContentAreaFilled(false);
        updateBtn.addActionListener(this::updateBtnActionPerformed);
        add(updateBtn);
        updateBtn.setBounds(560, 290, 110, 50);

        jLabel7.setText("Counselor Username");
        add(jLabel7);
        jLabel7.setBounds(20, 170, 110, 16);

        counselorUsernameTf1.addActionListener(this::counselorUsernameTf1ActionPerformed);
        add(counselorUsernameTf1);
        counselorUsernameTf1.setBounds(150, 163, 102, 30);

        createBtn.setContentAreaFilled(false);
        createBtn.addActionListener(this::createBtnActionPerformed);
        add(createBtn);
        createBtn.setBounds(310, 290, 230, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOPAssignment/Gui/manageAppointment 1_1.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(-250, 0, 933, 506);
    }// </editor-fold>//GEN-END:initComponents

    private void assignCounselorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignCounselorBtnActionPerformed
        String appointmentId = appointmentIdTf.getText();
        String newCounselorUsername = counselorUsernameTf1.getText();

        if (Validator.isEmpty(appointmentId) || Validator.isEmpty(newCounselorUsername)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter appointment ID and counselor username!");
            return;
        }

        Appointment appointment = Appointment.findById(appointmentId);
        if (appointment == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Appointment not found!");
            return;
        }

        appointment.setCounselorUsername(newCounselorUsername);
        appointment.save();

        javax.swing.JOptionPane.showMessageDialog(this, "Counselor assigned successfully!");
        refreshData();
    }//GEN-LAST:event_assignCounselorBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
         String appointmentId = appointmentIdTf.getText();

        if (Validator.isEmpty(appointmentId)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter appointment ID to cancel!");
            return;
        }

        boolean success = Appointment.cancelById(appointmentId);

        if (success) {
            javax.swing.JOptionPane.showMessageDialog(this, "Appointment cancelled successfully!");
            appointmentIdTf.setText("");
            refreshData();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Appointment not found!");
        }
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void typeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeComboActionPerformed

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
       String appointmentId = appointmentIdTf.getText();

        if (Validator.isEmpty(appointmentId)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter appointment ID to confirm!");
            return;
        }

        Appointment appointment = Appointment.findById(appointmentId);
        if (appointment == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Appointment not found!");
            return;
        }

        appointment.setStatus("Confirmed");
        appointment.save();

        javax.swing.JOptionPane.showMessageDialog(this, "Appointment confirmed successfully!");
        appointmentIdTf.setText("");
        refreshData();
    }//GEN-LAST:event_confirmBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        String appointmentId = appointmentIdTf.getText();

        if (Validator.isEmpty(appointmentId)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter appointment ID to update!");
            return;
        }

        Appointment appointment = Appointment.findById(appointmentId);
        if (appointment == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Appointment not found!");
            return;
        }

        java.util.Date selectedDate = (java.util.Date) dateSpinner.getValue();
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        String newDate = sdf.format(selectedDate);

        String newTime = timeTf.getText();
        String newType = (String) typeCombo.getSelectedItem();

        if (!Validator.isEmpty(newTime) && !Validator.isValidTime(newTime)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid time in HH:MM format (e.g. 09:00)!");
            return;
        }

        if (!newDate.equals(appointment.getDate())) {
            appointment.setDate(newDate);
        }
        if (!Validator.isEmpty(newTime)) {
            appointment.setTime(newTime);
        }
        appointment.setType(newType);

        appointment.save();

        javax.swing.JOptionPane.showMessageDialog(this, "Appointment updated successfully!");
        appointmentIdTf.setText("");
        timeTf.setText("");
        refreshData();
    }//GEN-LAST:event_updateBtnActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        String appointmentId = appointmentIdTf.getText();

        if (Validator.isEmpty(appointmentId)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter appointment ID to update!");
            return;
        }

        Appointment appointment = Appointment.findById(appointmentId);
        if (appointment == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Appointment not found!");
            return;
        }

        java.util.Date selectedDate = (java.util.Date) dateSpinner.getValue();
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        String newDate = sdf.format(selectedDate);

        String newTime = timeTf.getText();
        String newType = (String) typeCombo.getSelectedItem();

        if (!Validator.isEmpty(newTime) && !Validator.isValidTime(newTime)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid time in HH:MM format (e.g. 09:00)!");
            return;
        }

        if (!newDate.equals(appointment.getDate())) {
            appointment.setDate(newDate);
        }
        if (!Validator.isEmpty(newTime)) {
            appointment.setTime(newTime);
        }
        appointment.setType(newType);

        appointment.save();

        javax.swing.JOptionPane.showMessageDialog(this, "Appointment updated successfully!");
        appointmentIdTf.setText("");
        timeTf.setText("");
        refreshData();
    }//GEN-LAST:event_updateBtnActionPerformed


    private boolean studentExists(String studentUsername) {
        String[] lines = OOPAssignment.util.FileHandler.readAllLines("students.txt");
        for (String line : lines) {
            if (line.trim().isEmpty()) continue;
            String[] parts = line.split("\\|");
            if (parts.length >= 3 && parts[2].trim().equalsIgnoreCase(studentUsername)) {
                return true;
            }
        }
        return false;             
    }//GEN-LAST:event_createBtnActionPerformed

    private void studentUsernameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentUsernameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentUsernameTfActionPerformed

    private void counselorUsernameTf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_counselorUsernameTf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_counselorUsernameTf1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField appointmentIdTf;
    private javax.swing.JTextArea appointmentListArea;
    private javax.swing.JButton assignCounselorBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JTextField counselorUsernameTf1;
    private javax.swing.JButton createBtn;
    private javax.swing.JSpinner dateSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField studentUsernameTf;
    private javax.swing.JTextField timeTf;
    private javax.swing.JComboBox<String> typeCombo;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
