/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package OOPAssignment.Gui;

public class ManageStudentPanel extends javax.swing.JPanel {

    public ManageStudentPanel() {
        initComponents();

        studentListArea.setEditable(false);
        refreshData();


        studentIdTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    nameTf.requestFocus();
                }
            }
        });


        nameTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    usernameTf.requestFocus();
                }
            }
        });


        usernameTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    passwordTf.requestFocus();
                }
            }
        });


        passwordTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    emailTf.requestFocus();
                }
            }
        });


        emailTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    addStudentBtnActionPerformed(null);
                }
            }
        });
    }

    private void refreshData() {
        java.util.List<OOPAssignment.model.Student> students = OOPAssignment.model.Student.loadAll();

        String result = "";
        if (students.isEmpty()) {
            result += "No students yet.\n";
        } else {
            for (OOPAssignment.model.Student s : students) {
                result += s.getStudentId() + " - " + s.getName() + " (" + s.getUsername() + ") - " + s.getEmail() + "\n";
            }
        }
        studentListArea.setText(result);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentIdTf = new javax.swing.JTextField();
        nameTf = new javax.swing.JTextField();
        passwordTf = new javax.swing.JTextField();
        emailTf = new javax.swing.JTextField();
        addStudentBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentListArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        usernameTf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        loadStudentBtn = new javax.swing.JButton();
        updateStudentBtn = new javax.swing.JButton();
        deleteStudentBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setLayout(null);

        studentIdTf.addActionListener(this::studentIdTfActionPerformed);
        add(studentIdTf);
        studentIdTf.setBounds(90, 70, 178, 30);
        add(nameTf);
        nameTf.setBounds(80, 130, 178, 30);
        add(passwordTf);
        passwordTf.setBounds(80, 233, 178, 30);

        emailTf.addActionListener(this::emailTfActionPerformed);
        add(emailTf);
        emailTf.setBounds(70, 293, 178, 30);

        addStudentBtn.setContentAreaFilled(false);
        addStudentBtn.addActionListener(this::addStudentBtnActionPerformed);
        add(addStudentBtn);
        addStudentBtn.setBounds(300, 320, 170, 40);

        studentListArea.setEditable(false);
        studentListArea.setColumns(20);
        studentListArea.setRows(5);
        studentListArea.setBorder(null);
        jScrollPane1.setViewportView(studentListArea);

        add(jScrollPane1);
        jScrollPane1.setBounds(300, 30, 390, 230);

        jLabel1.setText("Student ID");
        add(jLabel1);
        jLabel1.setBounds(20, 80, 61, 17);

        jLabel2.setText("username");
        add(jLabel2);
        jLabel2.setBounds(10, 190, 57, 17);

        jLabel4.setText("Name");
        add(jLabel4);
        jLabel4.setBounds(30, 140, 34, 17);

        jLabel5.setText("password");
        add(jLabel5);
        jLabel5.setBounds(10, 240, 58, 17);
        add(usernameTf);
        usernameTf.setBounds(80, 180, 178, 30);

        jLabel3.setText("Email");
        add(jLabel3);
        jLabel3.setBounds(30, 300, 32, 17);

        loadStudentBtn.setContentAreaFilled(false);
        loadStudentBtn.addActionListener(this::loadStudentBtnActionPerformed);
        add(loadStudentBtn);
        loadStudentBtn.setBounds(470, 410, 210, 50);

        updateStudentBtn.setContentAreaFilled(false);
        updateStudentBtn.addActionListener(this::updateStudentBtnActionPerformed);
        add(updateStudentBtn);
        updateStudentBtn.setBounds(280, 410, 170, 50);

        deleteStudentBtn.setContentAreaFilled(false);
        deleteStudentBtn.addActionListener(this::deleteStudentBtnActionPerformed);
        add(deleteStudentBtn);
        deleteStudentBtn.setBounds(490, 320, 180, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOPAssignment/Gui/receptionistmanagestudent 1.png"))); // NOI18N
        add(jLabel6);
        jLabel6.setBounds(-250, 0, 937, 506);
    }// </editor-fold>//GEN-END:initComponents

    private void studentIdTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIdTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIdTfActionPerformed

    private void addStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentBtnActionPerformed
    String name = nameTf.getText();
    String username = usernameTf.getText();
    String password = passwordTf.getText();
    String email = emailTf.getText();

    if (OOPAssignment.util.Validator.isEmpty(name)
            || OOPAssignment.util.Validator.isEmpty(username)
            || OOPAssignment.util.Validator.isEmpty(password)
            || OOPAssignment.util.Validator.isEmpty(email)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields!");
        return;
    }

    if (OOPAssignment.model.Student.findByUsername(username) != null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Username already exists!");
        return;
    }

    String studentId = OOPAssignment.model.Student.generateNextId();   // 自动生成,用户完全不用管

    OOPAssignment.model.Student newStudent = new OOPAssignment.model.Student(studentId, name, username, password, email);
    newStudent.save();

    javax.swing.JOptionPane.showMessageDialog(this, "Student added successfully! ID: " + studentId);
    nameTf.setText("");
    usernameTf.setText("");
    passwordTf.setText("");
    emailTf.setText("");
    refreshData();
    }//GEN-LAST:event_addStudentBtnActionPerformed

    private void emailTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTfActionPerformed

    private void loadStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadStudentBtnActionPerformed
    String studentId = studentIdTf.getText();

    if (OOPAssignment.util.Validator.isEmpty(studentId)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter Student ID to search!");
        return;
    }

    OOPAssignment.model.Student foundStudent = OOPAssignment.model.Student.findByStudentId(studentId);

    if (foundStudent != null) {
        usernameTf.setText(foundStudent.getUsername());
        nameTf.setText(foundStudent.getName());
        emailTf.setText(foundStudent.getEmail());
        javax.swing.JOptionPane.showMessageDialog(this, "Student found! You can now edit and click Update.");
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Student not found!");
    }
    }//GEN-LAST:event_loadStudentBtnActionPerformed

    private void updateStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStudentBtnActionPerformed
    String studentId = studentIdTf.getText();

    if (OOPAssignment.util.Validator.isEmpty(studentId)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter Student ID to update!");
        return;
    }

    OOPAssignment.model.Student existingStudent = OOPAssignment.model.Student.findByStudentId(studentId);

    if (existingStudent == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Student not found!");
        return;
    }

    String newName = nameTf.getText();
    String newEmail = emailTf.getText();

    if (!OOPAssignment.util.Validator.isEmpty(newName)) {
        existingStudent.setName(newName);
    }
    if (!OOPAssignment.util.Validator.isEmpty(newEmail)) {
        existingStudent.setEmail(newEmail);
    }

    existingStudent.save();

    javax.swing.JOptionPane.showMessageDialog(this, "Student updated successfully!");
    studentIdTf.setText("");
    nameTf.setText("");
    usernameTf.setText("");
    passwordTf.setText("");
    emailTf.setText("");
    refreshData();
    }//GEN-LAST:event_updateStudentBtnActionPerformed

    private void deleteStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStudentBtnActionPerformed
    String studentId = studentIdTf.getText();

    if (OOPAssignment.util.Validator.isEmpty(studentId)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter Student ID to delete!");
        return;
    }

    int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
        "Are you sure you want to delete this student?",
        "Confirm Delete",
        javax.swing.JOptionPane.YES_NO_OPTION);

    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        boolean success = OOPAssignment.model.Student.deleteByStudentId(studentId);

        if (success) {
            javax.swing.JOptionPane.showMessageDialog(this, "Student deleted successfully!");
            studentIdTf.setText("");
            nameTf.setText("");
            usernameTf.setText("");
            passwordTf.setText("");
            emailTf.setText("");
            refreshData();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Student not found!");
        }
    }
    }//GEN-LAST:event_deleteStudentBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStudentBtn;
    private javax.swing.JButton deleteStudentBtn;
    private javax.swing.JTextField emailTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadStudentBtn;
    private javax.swing.JTextField nameTf;
    private javax.swing.JTextField passwordTf;
    private javax.swing.JTextField studentIdTf;
    private javax.swing.JTextArea studentListArea;
    private javax.swing.JButton updateStudentBtn;
    private javax.swing.JTextField usernameTf;
    // End of variables declaration//GEN-END:variables
}
