/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package OOPAssignment.Gui;

/**
 *
 * @author Asus
 */
public class MenuPanel extends javax.swing.JPanel {

    /**
     * Creates new form MenuPanel
     */
    private MainFrame mainFrame;

    public MenuPanel(MainFrame mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        counselorBtn = new javax.swing.JButton();
        receptionistBtn = new javax.swing.JButton();
        adminBtn = new javax.swing.JButton();
        studentBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        counselorBtn.setContentAreaFilled(false);
        counselorBtn.addActionListener(this::counselorBtnActionPerformed);
        add(counselorBtn);
        counselorBtn.setBounds(300, 290, 140, 30);

        receptionistBtn.setContentAreaFilled(false);
        receptionistBtn.addActionListener(this::receptionistBtnActionPerformed);
        add(receptionistBtn);
        receptionistBtn.setBounds(495, 293, 130, 30);

        adminBtn.setBackground(java.awt.SystemColor.windowBorder);
        adminBtn.setContentAreaFilled(false);
        adminBtn.addActionListener(this::adminBtnActionPerformed);
        add(adminBtn);
        adminBtn.setBounds(110, 290, 140, 30);

        studentBtn.setContentAreaFilled(false);
        studentBtn.addActionListener(this::studentBtnActionPerformed);
        add(studentBtn);
        studentBtn.setBounds(680, 290, 140, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOPAssignment/Gui/menu_panel_correct_colors 1.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(-3, -4, 940, 510);
    }// </editor-fold>//GEN-END:initComponents

    private void receptionistBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptionistBtnActionPerformed
        mainFrame.showPanel("receptionistLogin");
    }//GEN-LAST:event_receptionistBtnActionPerformed

    private void counselorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_counselorBtnActionPerformed
        mainFrame.showPanel("counselorLogin");
    }//GEN-LAST:event_counselorBtnActionPerformed

    private void studentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentBtnActionPerformed
        mainFrame.showPanel("studentLogin");
    }//GEN-LAST:event_studentBtnActionPerformed

    private void adminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminBtnActionPerformed
        mainFrame.showPanel("adminLogin");
    }//GEN-LAST:event_adminBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminBtn;
    private javax.swing.JButton counselorBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton receptionistBtn;
    private javax.swing.JButton studentBtn;
    // End of variables declaration//GEN-END:variables
}
