/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package OOPAssignment.Gui;

import OOPAssignment.model.Appointment;
import OOPAssignment.model.User;
import java.util.List;

public class MyAppointmentsPanel extends javax.swing.JPanel {

    private User counselor;

    public MyAppointmentsPanel(User counselor) {
        initComponents();
        this.counselor = counselor;

        appointmentsArea.setEditable(false);
        refreshData();
    }

    private void refreshData() {
        List<Appointment> myAppointments = Appointment.findByCounselor(counselor.getUsername());

        String result = "=== My Appointments ===\n";
        if (myAppointments.isEmpty()) {
            result += "No appointments assigned yet.\n";
        } else {
            for (Appointment a : myAppointments) {
                result += a.getDate() + " " + a.getTime() + " - Student: " + a.getStudentUsername()
                        + " - Status: " + a.getStatus() + "\n";
            }
        }
        appointmentsArea.setText(result);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        appointmentsArea = new javax.swing.JTextArea();
        refreshBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        appointmentsArea.setColumns(20);
        appointmentsArea.setRows(5);
        jScrollPane1.setViewportView(appointmentsArea);

        add(jScrollPane1);
        jScrollPane1.setBounds(40, 100, 670, 370);

        refreshBtn.setContentAreaFilled(false);
        refreshBtn.addActionListener(this::refreshBtnActionPerformed);
        add(refreshBtn);
        refreshBtn.setBounds(620, 40, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOPAssignment/Gui/counselor_appointments_preview.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(-190, 0, 930, 510);
    }// </editor-fold>//GEN-END:initComponents

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        refreshData();
    }//GEN-LAST:event_refreshBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea appointmentsArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshBtn;
    // End of variables declaration//GEN-END:variables
}
