/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package OOPAssignment.Gui;

import OOPAssignment.model.Admin;
import OOPAssignment.model.User;

public class MyRosterPanel extends javax.swing.JPanel {

    private Admin admin;
    private User counselor;

    public MyRosterPanel(Admin admin, User counselor) {
        initComponents();
        this.admin = admin;
        this.counselor = counselor;

        scheduleArea.setEditable(false);
        scheduleArea.setText(admin.viewScheduleForStaff(counselor.getName()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        scheduleArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        scheduleArea.setEditable(false);
        scheduleArea.setColumns(20);
        scheduleArea.setRows(5);
        jScrollPane1.setViewportView(scheduleArea);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 100, 670, 370);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOPAssignment/Gui/counselor_roster_preview.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(-200, -10, 930, 520);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea scheduleArea;
    // End of variables declaration//GEN-END:variables
}
