/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package OOPAssignment.Gui;

import OOPAssignment.model.Appointment;
import OOPAssignment.model.Student;
import OOPAssignment.util.Validator;
import java.util.List;

public class QueuePanel extends javax.swing.JPanel {

    private int nextQueueNumber = 1;

    public QueuePanel() {
        initComponents();
        studentListArea.setEditable(false);
        refreshData();
    }

    private void refreshData() {
        // 显示预约列表(保留原本的功能)
        List<Appointment> allAppointments = Appointment.loadAll();
        String appointmentResult = "=== All Appointments ===\n";
        if (allAppointments.isEmpty()) {
            appointmentResult += "No appointments yet.\n";
        } else {
            for (Appointment a : allAppointments) {
                appointmentResult += a.getAppointmentId() + " - Student: " + a.getStudentUsername()
                        + " - Counselor: " + a.getCounselorUsername()
                        + " - " + a.getDate() + " " + a.getTime()
                        + " - Type: " + a.getType()
                        + " (" + a.getStatus() + ")\n";
            }
        }

        // 显示学生列表(新加的)
        List<Student> allStudents = Student.loadAll();
        String studentResult = "=== Student List ===\n";
        if (allStudents.isEmpty()) {
            studentResult += "No students yet.\n";
        } else {
            for (Student s : allStudents) {
                String queueInfo = (s.getQueueNumber() == -1) ? "No queue number" : "Queue #" + s.getQueueNumber();
                studentResult += s.getStudentId() + " - " + s.getName() + " (" + s.getUsername() + ") - " + queueInfo + "\n";
            }
        }
        studentListArea.setText(studentResult);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentIdTf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        generateBtn = new javax.swing.JButton();
        resultLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentListArea = new javax.swing.JTextArea();

        jLabel1.setText("Student ID");

        generateBtn.setText("Generate");
        generateBtn.addActionListener(this::generateBtnActionPerformed);

        resultLbl.setText("Result");

        studentListArea.setEditable(false);
        studentListArea.setColumns(20);
        studentListArea.setRows(5);
        jScrollPane1.setViewportView(studentListArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(studentIdTf, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(generateBtn))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(studentIdTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(generateBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultLbl)
                .addGap(134, 134, 134))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void generateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateBtnActionPerformed
        String studentId = studentIdTf.getText();

        if (Validator.isEmpty(studentId)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter Student ID!");
            return;
        }

        Student student = Student.findByStudentId(studentId);
        if (student == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Student not found!");
            return;
        }

        student.setQueueNumber(nextQueueNumber);
        student.save();

        resultLbl.setText("Queue number " + nextQueueNumber + " assigned to " + student.getName());
        nextQueueNumber++;
        studentIdTf.setText("");
        refreshData();
    }//GEN-LAST:event_generateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generateBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel resultLbl;
    private javax.swing.JTextField studentIdTf;
    private javax.swing.JTextArea studentListArea;
    // End of variables declaration//GEN-END:variables
}
