/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package OOPAssignment.Gui;

import OOPAssignment.model.Student;

public class QueueStatusPanel extends javax.swing.JPanel {

    public QueueStatusPanel(Student student) {
        initComponents();

        int queueNumber = student.getQueueNumber();
        if (queueNumber == -1) {
            queueLbl.setText("No queue number assigned yet.");
        } else {
            queueLbl.setText("Your queue number: " + queueNumber);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        queueLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        queueLbl.setBackground(new java.awt.Color(255, 255, 255));
        queueLbl.setForeground(new java.awt.Color(255, 255, 255));
        queueLbl.setText("queue");
        add(queueLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 60, 268, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOPAssignment/Gui/studentblank.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-440, -140, 1570, 790));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel queueLbl;
    // End of variables declaration//GEN-END:variables
}
