/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package OOPAssignment.Gui;

import OOPAssignment.model.Appointment;
import OOPAssignment.model.Student;
import OOPAssignment.util.Validator;
import java.util.List;

public class QueuePanel extends javax.swing.JPanel {

    private int nextQueueNumber = 1;

    public QueuePanel() {
        initComponents();
        studentListArea.setEditable(false);
        refreshData();
    }

    private void refreshData() {

        List<Appointment> allAppointments = Appointment.loadAll();
        String appointmentResult = "=== All Appointments ===\n";
        if (allAppointments.isEmpty()) {
            appointmentResult += "No appointments yet.\n";
        } else {
            for (Appointment a : allAppointments) {
                appointmentResult += a.getAppointmentId() + " - Student: " + a.getStudentUsername()
                        + " - Counselor: " + a.getCounselorUsername()
                        + " - " + a.getDate() + " " + a.getTime()
                        + " - Type: " + a.getType()
                        + " (" + a.getStatus() + ")\n";
            }
        }


        List<Student> allStudents = Student.loadAll();
        String studentResult = "=== Student List ===\n";
        if (allStudents.isEmpty()) {
            studentResult += "No students yet.\n";
        } else {
            for (Student s : allStudents) {
                String queueInfo = (s.getQueueNumber() == -1) ? "No queue number" : "Queue #" + s.getQueueNumber();
                studentResult += s.getStudentId() + " - " + s.getName() + " (" + s.getUsername() + ") - " + queueInfo + "\n";
            }
        }
        studentListArea.setText(studentResult);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentIdTf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        generateBtn = new javax.swing.JButton();
        resultLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentListArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);
        add(studentIdTf);
        studentIdTf.setBounds(90, 103, 175, 30);

        jLabel1.setText("Student ID");
        add(jLabel1);
        jLabel1.setBounds(20, 110, 61, 17);

        generateBtn.setText(" ");
        generateBtn.setContentAreaFilled(false);
        generateBtn.addActionListener(this::generateBtnActionPerformed);
        add(generateBtn);
        generateBtn.setBounds(310, 320, 110, 30);

        resultLbl.setText("Result");
        add(resultLbl);
        resultLbl.setBounds(310, 360, 112, 17);

        studentListArea.setEditable(false);
        studentListArea.setColumns(20);
        studentListArea.setRows(5);
        jScrollPane1.setViewportView(studentListArea);

        add(jScrollPane1);
        jScrollPane1.setBounds(300, 30, 360, 250);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOPAssignment/Gui/Queue 1.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(-250, 0, 937, 506);
    }// </editor-fold>//GEN-END:initComponents

    private void generateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateBtnActionPerformed
        String studentId = studentIdTf.getText();

        if (Validator.isEmpty(studentId)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter Student ID!");
            return;
        }

        Student student = Student.findByStudentId(studentId);
        if (student == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Student not found!");
            return;
        }

        student.setQueueNumber(nextQueueNumber);
        student.save();

        resultLbl.setText("Queue number " + nextQueueNumber + " assigned to " + student.getName());
        nextQueueNumber++;
        studentIdTf.setText("");
        refreshData();
    }//GEN-LAST:event_generateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generateBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel resultLbl;
    private javax.swing.JTextField studentIdTf;
    private javax.swing.JTextArea studentListArea;
    // End of variables declaration//GEN-END:variables
}
