/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package OOPAssignment.Gui;

import OOPAssignment.model.Admin;
import OOPAssignment.model.User;
import OOPAssignment.model.Receptionist;

public class ReceptionistLoginPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;
    private Admin admin;

    public ReceptionistLoginPanel(MainFrame mainFrame, Admin admin) {
        initComponents();
        this.mainFrame = mainFrame;
        this.admin = admin;

        usernameTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    passwordTf.requestFocus();
                }
            }
        });

        passwordTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    loginBtnActionPerformed(null);
                }
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        loginBtn = new javax.swing.JButton();
        passwordTf = new javax.swing.JPasswordField();
        usernameTf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(null);

        backBtn.setAutoscrolls(true);
        backBtn.setBorderPainted(false);
        backBtn.setContentAreaFilled(false);
        backBtn.setFocusPainted(false);
        backBtn.addActionListener(this::backBtnActionPerformed);
        add(backBtn);
        backBtn.setBounds(510, 360, 90, 30);

        loginBtn.setBorderPainted(false);
        loginBtn.setContentAreaFilled(false);
        loginBtn.setFocusPainted(false);
        loginBtn.addActionListener(this::loginBtnActionPerformed);
        add(loginBtn);
        loginBtn.setBounds(340, 360, 90, 30);

        passwordTf.setBackground(new java.awt.Color(51, 51, 51));
        passwordTf.setForeground(new java.awt.Color(255, 255, 255));
        passwordTf.setBorder(null);
        passwordTf.addActionListener(this::passwordTfActionPerformed);
        add(passwordTf);
        passwordTf.setBounds(370, 270, 240, 40);

        usernameTf.setBackground(new java.awt.Color(51, 51, 51));
        usernameTf.setForeground(new java.awt.Color(255, 255, 255));
        usernameTf.setBorder(null);
        usernameTf.setOpaque(true);
        usernameTf.addActionListener(this::usernameTfActionPerformed);
        add(usernameTf);
        usernameTf.setBounds(370, 190, 240, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOPAssignment/Gui/apulogo (1).png"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(50, 30, 110, 100);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOPAssignment/Gui/Receptionist login.png"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(0, 0, 940, 505);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTfActionPerformed

    private void passwordTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTfActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
    String inputUsername = usernameTf.getText();
    String inputPassword = passwordTf.getText();

    User foundStaff = admin.findStaffByUsername(inputUsername);

    if (foundStaff != null && foundStaff.login(inputUsername, inputPassword) 
            && foundStaff instanceof Receptionist) {
        javax.swing.JOptionPane.showMessageDialog(this, "Login successful!");
        mainFrame.showReceptionistPanel(foundStaff);
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Wrong username or password!");
    }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        mainFrame.showPanel("menu");
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passwordTf;
    private javax.swing.JTextField usernameTf;
    // End of variables declaration//GEN-END:variables

}
