/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package OOPAssignment.Gui;

import OOPAssignment.model.Admin;
import OOPAssignment.model.Receptionist;
import OOPAssignment.model.User;
import java.awt.CardLayout;

public class ReceptionistPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;
    private Admin admin;
    private User loggedInReceptionist;
    private CardLayout innerCardLayout;
    private ReceptionistDashboardPanel dashboardPanel;

    public ReceptionistPanel(MainFrame mainFrame, Admin admin, User loggedInReceptionist) {
        initComponents();
        this.mainFrame = mainFrame;
        this.admin = admin;
        this.loggedInReceptionist = loggedInReceptionist;

        innerCardLayout = new CardLayout();
        contentPanel.setLayout(innerCardLayout);

        dashboardPanel = new ReceptionistDashboardPanel(loggedInReceptionist);
        contentPanel.add(dashboardPanel, "dashboard");

        contentPanel.add(new ManageStudentPanel(), "manageStudent");
        contentPanel.add(new ManageAppointmentPanel(admin), "manageAppointment");
        contentPanel.add(new QueuePanel(), "queue");

        innerCardLayout.show(contentPanel, "dashboard");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboardBtn = new javax.swing.JButton();
        manageStudentBtn = new javax.swing.JButton();
        manageAppointmentBtn = new javax.swing.JButton();
        queueBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        DashBoardLbl = new javax.swing.JLabel();
        ManageAppointmentLbl = new javax.swing.JLabel();
        ManageStudentLbl = new javax.swing.JLabel();
        QueueLbl = new javax.swing.JLabel();

        setLayout(null);

        dashboardBtn.setContentAreaFilled(false);
        dashboardBtn.addActionListener(this::dashboardBtnActionPerformed);
        add(dashboardBtn);
        dashboardBtn.setBounds(20, 170, 230, 40);

        manageStudentBtn.setContentAreaFilled(false);
        manageStudentBtn.addActionListener(this::manageStudentBtnActionPerformed);
        add(manageStudentBtn);
        manageStudentBtn.setBounds(20, 230, 220, 30);

        manageAppointmentBtn.setContentAreaFilled(false);
        manageAppointmentBtn.addActionListener(this::manageAppointmentBtnActionPerformed);
        add(manageAppointmentBtn);
        manageAppointmentBtn.setBounds(20, 290, 220, 30);

        queueBtn.setContentAreaFilled(false);
        queueBtn.addActionListener(this::queueBtnActionPerformed);
        add(queueBtn);
        queueBtn.setBounds(20, 350, 220, 30);

        logoutBtn.setToolTipText("");
        logoutBtn.setContentAreaFilled(false);
        logoutBtn.addActionListener(this::logoutBtnActionPerformed);
        add(logoutBtn);
        logoutBtn.setBounds(20, 470, 120, 30);

        contentPanel.setMaximumSize(new java.awt.Dimension(808, 500));
        contentPanel.setLayout(new java.awt.CardLayout());
        add(contentPanel);
        contentPanel.setBounds(250, 0, 700, 506);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOPAssignment/Gui/apulogo (1).png"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(70, 10, 110, 110);

        DashBoardLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOPAssignment/Gui/ReceptionistDashboard1.png"))); // NOI18N
        add(DashBoardLbl);
        DashBoardLbl.setBounds(0, 0, 933, 506);

        ManageAppointmentLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOPAssignment/Gui/manageAppointment 1.png"))); // NOI18N
        add(ManageAppointmentLbl);
        ManageAppointmentLbl.setBounds(0, 0, 937, 506);

        ManageStudentLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOPAssignment/Gui/receptionistmanagestudent 1.png"))); // NOI18N
        add(ManageStudentLbl);
        ManageStudentLbl.setBounds(0, 0, 700, 506);

        QueueLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOPAssignment/Gui/Queue 1.png"))); // NOI18N
        add(QueueLbl);
        QueueLbl.setBounds(0, 0, 937, 506);
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
        innerCardLayout.show(contentPanel, "dashboard");
        ManageStudentLbl.setVisible(false);
        DashBoardLbl.setVisible(true);
        ManageAppointmentLbl.setVisible(false);
        QueueLbl.setVisible(false);
        dashboardPanel.refreshStats();
    
    for (java.awt.Component comp : contentPanel.getComponents()) {
            if (comp instanceof ReceptionistDashboardPanel) {
                ((ReceptionistDashboardPanel) comp).refreshStats();
                break;
            }
        }   
    }//GEN-LAST:event_dashboardBtnActionPerformed

    private void manageStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageStudentBtnActionPerformed

       innerCardLayout.show(contentPanel, "manageStudent");
       ManageStudentLbl.setVisible(true);
        DashBoardLbl.setVisible(false);
        ManageAppointmentLbl.setVisible(false);
        QueueLbl.setVisible(false);
    }//GEN-LAST:event_manageStudentBtnActionPerformed

    private void manageAppointmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAppointmentBtnActionPerformed
        innerCardLayout.show(contentPanel, "manageAppointment");
        ManageStudentLbl.setVisible(false);
        DashBoardLbl.setVisible(false);
        ManageAppointmentLbl.setVisible(true);
        QueueLbl.setVisible(false);

    }//GEN-LAST:event_manageAppointmentBtnActionPerformed

    private void queueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queueBtnActionPerformed
       innerCardLayout.show(contentPanel, "queue");
        ManageStudentLbl.setVisible(false);
        DashBoardLbl.setVisible(false);
        ManageAppointmentLbl.setVisible(false);
        QueueLbl.setVisible(true);

    }//GEN-LAST:event_queueBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        mainFrame.showPanel("menu");
    }//GEN-LAST:event_logoutBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DashBoardLbl;
    private javax.swing.JLabel ManageAppointmentLbl;
    private javax.swing.JLabel ManageStudentLbl;
    private javax.swing.JLabel QueueLbl;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton dashboardBtn;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton manageAppointmentBtn;
    private javax.swing.JButton manageStudentBtn;
    private javax.swing.JButton queueBtn;
    // End of variables declaration//GEN-END:variables
}
