/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package OOPAssignment.Gui;

import OOPAssignment.model.Admin;
import OOPAssignment.model.User;
import java.awt.CardLayout;

public class ReceptionistPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;
    private Admin admin;
    private User loggedInReceptionist;
    private CardLayout innerCardLayout;

    public ReceptionistPanel(MainFrame mainFrame, Admin admin, User loggedInReceptionist) {
        initComponents();
        this.mainFrame = mainFrame;
        this.admin = admin;
        this.loggedInReceptionist = loggedInReceptionist;

        innerCardLayout = new CardLayout();
        contentPanel.setLayout(innerCardLayout);

        contentPanel.add(new ReceptionistDashboardPanel(loggedInReceptionist), "dashboard");
        contentPanel.add(new ManageStudentPanel(), "manageStudent");
        contentPanel.add(new ManageAppointmentPanel(admin), "manageAppointment");
        contentPanel.add(new QueuePanel(), "queue");

        innerCardLayout.show(contentPanel, "dashboard");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        dashboardBtn = new javax.swing.JButton();
        manageStudentBtn = new javax.swing.JButton();
        manageAppointmentBtn = new javax.swing.JButton();
        queueBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        contentPanel = new javax.swing.JPanel();

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOPAssignment/Gui/apulogo (1).png"))); // NOI18N

        dashboardBtn.setText("Dashboard");
        dashboardBtn.addActionListener(this::dashboardBtnActionPerformed);

        manageStudentBtn.setText("Manage Student");
        manageStudentBtn.addActionListener(this::manageStudentBtnActionPerformed);

        manageAppointmentBtn.setText("Manage Appointment");
        manageAppointmentBtn.addActionListener(this::manageAppointmentBtnActionPerformed);

        queueBtn.setText("Queue");
        queueBtn.addActionListener(this::queueBtnActionPerformed);

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(this::logoutBtnActionPerformed);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        contentPanel.setMaximumSize(new java.awt.Dimension(808, 500));
        contentPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(manageAppointmentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(logoutBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 779, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dashboardBtn)
                                    .addComponent(jLabel5))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addComponent(queueBtn)))
                            .addGap(33, 33, 33))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(manageStudentBtn)
                            .addGap(21, 21, 21)))
                    .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(manageAppointmentBtn)
                .addGap(99, 99, 99)
                .addComponent(logoutBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(26, 26, 26)
                            .addComponent(dashboardBtn)
                            .addGap(27, 27, 27)
                            .addComponent(manageStudentBtn)
                            .addGap(91, 91, 91)
                            .addComponent(queueBtn)
                            .addGap(0, 176, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
        innerCardLayout.show(contentPanel, "dashboard");
    }//GEN-LAST:event_dashboardBtnActionPerformed

    private void manageStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageStudentBtnActionPerformed

       innerCardLayout.show(contentPanel, "manageStudent");
    }//GEN-LAST:event_manageStudentBtnActionPerformed

    private void manageAppointmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAppointmentBtnActionPerformed
        innerCardLayout.show(contentPanel, "manageAppointment");

    }//GEN-LAST:event_manageAppointmentBtnActionPerformed

    private void queueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queueBtnActionPerformed
       innerCardLayout.show(contentPanel, "queue");

    }//GEN-LAST:event_queueBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        mainFrame.showPanel("menu");
    }//GEN-LAST:event_logoutBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton dashboardBtn;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton manageAppointmentBtn;
    private javax.swing.JButton manageStudentBtn;
    private javax.swing.JButton queueBtn;
    // End of variables declaration//GEN-END:variables
}
