/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package OOPAssignment.Gui;

import OOPAssignment.model.Admin;

public class ReportsPanel extends javax.swing.JPanel {

    private Admin admin;

    public ReportsPanel(Admin admin) {
        initComponents();
        this.admin = admin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reportTypeCombo = new javax.swing.JComboBox<>();
        generateBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        reportTypeCombo.setBackground(new java.awt.Color(34, 34, 38));
        reportTypeCombo.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        reportTypeCombo.setForeground(new java.awt.Color(204, 204, 204));
        reportTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Daily", "Monthly", "Quarterly", "Yearly" }));
        reportTypeCombo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(reportTypeCombo);
        reportTypeCombo.setBounds(50, 110, 170, 30);

        generateBtn.setContentAreaFilled(false);
        generateBtn.addActionListener(this::generateBtnActionPerformed);
        add(generateBtn);
        generateBtn.setBounds(60, 143, 240, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOPAssignment/Gui/AdminManageStaff.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(932, 507));
        jLabel1.setMinimumSize(new java.awt.Dimension(932, 507));
        add(jLabel1);
        jLabel1.setBounds(-170, 0, 930, 510);
    }// </editor-fold>//GEN-END:initComponents

    private void generateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateBtnActionPerformed
        String type = (String) reportTypeCombo.getSelectedItem();

        boolean success = admin.generateReport(type.toLowerCase());

        if (success) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                type + " report generated successfully!\nSaved as: " + type.toLowerCase() + "_report.txt");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Failed to generate report!");
        }
    
    }//GEN-LAST:event_generateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generateBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> reportTypeCombo;
    // End of variables declaration//GEN-END:variables
}
