/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package OOPAssignment.Gui;

import OOPAssignment.model.Admin;
import OOPAssignment.util.Validator;

public class RosterPanel extends javax.swing.JPanel {

    private Admin admin;

    public RosterPanel(Admin admin) {
        initComponents();
        this.admin = admin;
        javax.swing.SpinnerDateModel dateModel = new javax.swing.SpinnerDateModel();
        dateSpinner.setModel(dateModel);
        javax.swing.JSpinner.DateEditor dateEditor = new javax.swing.JSpinner.DateEditor(dateSpinner, "yyyy-MM-dd");
        dateSpinner.setEditor(dateEditor);
        dateEditor.getTextField().setBackground(new java.awt.Color(34,34,38));
        dateEditor.getTextField().setForeground(new java.awt.Color(204, 204, 204));
        refreshData();
        dateSpinner.setBackground(new java.awt.Color(45, 45, 50));
    }

    private void refreshData() {
        scheduleListArea.setText(admin.viewSchedule());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        staffNameTf = new javax.swing.JTextField();
        addScheduleBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        scheduleListArea = new javax.swing.JTextArea();
        startTimeTf = new javax.swing.JTextField();
        dateSpinner = new javax.swing.JSpinner();
        endTimeTf = new javax.swing.JTextField();
        deleteScheduleBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        staffNameTf.setBackground(new java.awt.Color(45, 45, 50));
        staffNameTf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        staffNameTf.setForeground(new java.awt.Color(153, 153, 153));
        staffNameTf.setBorder(null);
        staffNameTf.addActionListener(this::staffNameTfActionPerformed);
        add(staffNameTf);
        staffNameTf.setBounds(60, 95, 290, 20);

        addScheduleBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addScheduleBtn.setContentAreaFilled(false);
        addScheduleBtn.addActionListener(this::addScheduleBtnActionPerformed);
        add(addScheduleBtn);
        addScheduleBtn.setBounds(60, 200, 140, 30);

        scheduleListArea.setEditable(false);
        scheduleListArea.setBackground(new java.awt.Color(20, 20, 22));
        scheduleListArea.setColumns(20);
        scheduleListArea.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        scheduleListArea.setForeground(new java.awt.Color(204, 204, 204));
        scheduleListArea.setRows(5);
        scheduleListArea.setText("wadawdawdawdawd");
        scheduleListArea.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        scheduleListArea.setFocusable(false);
        jScrollPane1.setViewportView(scheduleListArea);

        add(jScrollPane1);
        jScrollPane1.setBounds(40, 310, 710, 160);

        startTimeTf.setBackground(new java.awt.Color(45, 45, 50));
        startTimeTf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        startTimeTf.setForeground(new java.awt.Color(153, 153, 153));
        startTimeTf.setBorder(null);
        startTimeTf.addActionListener(this::startTimeTfActionPerformed);
        add(startTimeTf);
        startTimeTf.setBounds(60, 150, 130, 20);

        dateSpinner.setToolTipText("");
        dateSpinner.setBorder(null);
        add(dateSpinner);
        dateSpinner.setBounds(360, 150, 160, 30);

        endTimeTf.setBackground(new java.awt.Color(45, 45, 50));
        endTimeTf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        endTimeTf.setForeground(new java.awt.Color(153, 153, 153));
        endTimeTf.setBorder(null);
        endTimeTf.addActionListener(this::endTimeTfActionPerformed);
        add(endTimeTf);
        endTimeTf.setBounds(220, 150, 130, 20);

        deleteScheduleBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteScheduleBtn.setContentAreaFilled(false);
        deleteScheduleBtn.addActionListener(this::deleteScheduleBtnActionPerformed);
        add(deleteScheduleBtn);
        deleteScheduleBtn.setBounds(230, 200, 130, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOPAssignment/Gui/roster_schedule_clear 1 (1).png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(932, 507));
        jLabel1.setMinimumSize(new java.awt.Dimension(932, 507));
        add(jLabel1);
        jLabel1.setBounds(-170, -10, 950, 510);
    }// </editor-fold>//GEN-END:initComponents

    private void staffNameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffNameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffNameTfActionPerformed

    private void addScheduleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addScheduleBtnActionPerformed

        String staffName = staffNameTf.getText();

        java.util.Date selectedDate = (java.util.Date) dateSpinner.getValue();
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        String date = sdf.format(selectedDate);

        String startTime = startTimeTf.getText();
        String endTime = endTimeTf.getText();

        if (Validator.isEmpty(staffName) || Validator.isEmpty(startTime) || Validator.isEmpty(endTime)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields!");
            return;
        }

        if (startTime.equals(endTime)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Start time and end time cannot be the same!");
            return;
        }

        if (!admin.isStaffExist(staffName)) {
            javax.swing.JOptionPane.showMessageDialog(this, "This staff does not exist! Please check the name.");
            return;
        }

        boolean success = admin.addSchedule(staffName, date, startTime, endTime);

        if (success) {
            javax.swing.JOptionPane.showMessageDialog(this, "Schedule added successfully!");
            staffNameTf.setText("");
            startTimeTf.setText("");
            endTimeTf.setText("");
            refreshData();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Failed to add schedule!");
        }
    }//GEN-LAST:event_addScheduleBtnActionPerformed

    private void startTimeTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startTimeTfActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_startTimeTfActionPerformed

    private void endTimeTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endTimeTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endTimeTfActionPerformed

    private void deleteScheduleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteScheduleBtnActionPerformed
        String staffName = staffNameTf.getText();

        java.util.Date selectedDate = (java.util.Date) dateSpinner.getValue();
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        String date = sdf.format(selectedDate);

        if (Validator.isEmpty(staffName)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter the staff name to delete!");
            return;
        }

        boolean success = admin.deleteSchedule(staffName, date);

        if (success) {
            javax.swing.JOptionPane.showMessageDialog(this, "Schedule deleted successfully!");
            staffNameTf.setText("");
            refreshData();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Schedule not found! Please check name and date.");
        }

    }//GEN-LAST:event_deleteScheduleBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addScheduleBtn;
    private javax.swing.JSpinner dateSpinner;
    private javax.swing.JButton deleteScheduleBtn;
    private javax.swing.JTextField endTimeTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea scheduleListArea;
    private javax.swing.JTextField staffNameTf;
    private javax.swing.JTextField startTimeTf;
    // End of variables declaration//GEN-END:variables
}
