/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package OOPAssignment.Gui;

import OOPAssignment.model.Admin;
import OOPAssignment.model.Student;
import java.awt.CardLayout;

public class StudentPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;
    private Admin admin;
    private Student loggedInStudent;
    private CardLayout innerCardLayout;

    public StudentPanel(MainFrame mainFrame, Admin admin, Student loggedInStudent) {
        initComponents();
        this.mainFrame = mainFrame;
        this.admin = admin;
        this.loggedInStudent = loggedInStudent;

        innerCardLayout = new CardLayout();
        contentPanel.setLayout(innerCardLayout);

        contentPanel.add(new StudentDashboardPanel(loggedInStudent), "dashboard");
        contentPanel.add(new BookAppointmentPanel(loggedInStudent), "book");
        contentPanel.add(new MyAppointmentHistoryPanel(loggedInStudent), "history");
        contentPanel.add(new CounselorProfilesPanel(admin), "profiles");
        contentPanel.add(new QueueStatusPanel(loggedInStudent), "queue");

        innerCardLayout.show(contentPanel, "dashboard");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        dashboardBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        bookBtn = new javax.swing.JButton();
        historyBtn = new javax.swing.JButton();
        profilesBtn = new javax.swing.JButton();
        queueBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        dashboardBtn.setText("dashboard");
        dashboardBtn.addActionListener(this::dashboardBtnActionPerformed);

        jLabel1.setText("Student");

        logoutBtn.setText("log out");
        logoutBtn.addActionListener(this::logoutBtnActionPerformed);

        contentPanel.setLayout(new java.awt.CardLayout());

        bookBtn.setText("Book");
        bookBtn.addActionListener(this::bookBtnActionPerformed);

        historyBtn.setText("history");
        historyBtn.addActionListener(this::historyBtnActionPerformed);

        profilesBtn.setText("profiles");
        profilesBtn.addActionListener(this::profilesBtnActionPerformed);

        queueBtn.setText("Queue");
        queueBtn.addActionListener(this::queueBtnActionPerformed);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanel1.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookBtn)
                    .addComponent(profilesBtn)
                    .addComponent(queueBtn)
                    .addComponent(logoutBtn)
                    .addComponent(historyBtn)
                    .addComponent(dashboardBtn))
                .addGap(78, 78, 78)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 386, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(185, 185, 185)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(745, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(135, 135, 135)
                .addComponent(dashboardBtn)
                .addGap(18, 18, 18)
                .addComponent(historyBtn)
                .addGap(18, 18, 18)
                .addComponent(bookBtn)
                .addGap(18, 18, 18)
                .addComponent(profilesBtn)
                .addGap(18, 18, 18)
                .addComponent(queueBtn)
                .addGap(18, 18, 18)
                .addComponent(logoutBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                    .addGap(2, 2, 2)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
       mainFrame.showPanel("menu");
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
        innerCardLayout.show(contentPanel, "dashboard");
    }//GEN-LAST:event_dashboardBtnActionPerformed

    private void queueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queueBtnActionPerformed
        innerCardLayout.show(contentPanel, "queue");
    }//GEN-LAST:event_queueBtnActionPerformed

    private void bookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookBtnActionPerformed
        innerCardLayout.show(contentPanel, "book");
    }//GEN-LAST:event_bookBtnActionPerformed

    private void historyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyBtnActionPerformed
        innerCardLayout.show(contentPanel, "history");
    }//GEN-LAST:event_historyBtnActionPerformed

    private void profilesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilesBtnActionPerformed
        innerCardLayout.show(contentPanel, "profiles");
    }//GEN-LAST:event_profilesBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookBtn;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton dashboardBtn;
    private javax.swing.JButton historyBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton profilesBtn;
    private javax.swing.JButton queueBtn;
    // End of variables declaration//GEN-END:variables
}
