/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package OOPAssignment.Gui;
    
import OOPAssignment.model.Student;
import OOPAssignment.model.Appointment;
import java.util.List;
import java.time.LocalDate;

public class StudentDashboardPanel extends javax.swing.JPanel {

    private Student student;

    public StudentDashboardPanel(Student student) {
        initComponents();
        this.student = student;

        loadDashboard();    
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dateValueLbl = new javax.swing.JLabel();
        timeValueLbl = new javax.swing.JLabel();
        counselorValueLbl = new javax.swing.JLabel();
        statusValueLbl = new javax.swing.JLabel();
        queueValueLbl = new javax.swing.JLabel();
        waitingValueLbl = new javax.swing.JLabel();
        png = new javax.swing.JLabel();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeLbl.setBackground(new java.awt.Color(255, 255, 255));
        welcomeLbl.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLbl.setText("                   Student Dashboard");
        add(welcomeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 230, 60));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TP102292");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 70, 30));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TP102292@mail.apu.edu.my");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, -1, -1));

        dateValueLbl.setForeground(new java.awt.Color(255, 255, 255));
        dateValueLbl.setText("jLabel1");
        add(dateValueLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        timeValueLbl.setForeground(new java.awt.Color(255, 255, 255));
        timeValueLbl.setText("jLabel5");
        add(timeValueLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        counselorValueLbl.setForeground(new java.awt.Color(255, 255, 255));
        counselorValueLbl.setText("jLabel6");
        add(counselorValueLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        statusValueLbl.setForeground(new java.awt.Color(255, 255, 255));
        statusValueLbl.setText("jLabel7");
        add(statusValueLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, -1, -1));

        queueValueLbl.setForeground(new java.awt.Color(255, 255, 255));
        queueValueLbl.setText("jLabel1");
        add(queueValueLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, -1));

        waitingValueLbl.setForeground(new java.awt.Color(255, 255, 255));
        waitingValueLbl.setText("jLabel2");
        add(waitingValueLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, -1, -1));

        png.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOPAssignment/Gui/StudentDashboard_933x506.png"))); // NOI18N
        add(png, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded

    }//GEN-LAST:event_formAncestorAdded
    private void loadDashboard() {

    welcomeLbl.setText("Welcome, " + student.getName());
    jLabel3.setText(student.getStudentId());
    jLabel4.setText(student.getEmail());

    // Get all appointments for this student
    List<Appointment> appointments =
            Appointment.findByStudent(student.getUsername());

    Appointment upcoming = null;

    for (Appointment a : appointments) {

        // Ignore cancelled or completed appointments
        if (a.getStatus().equalsIgnoreCase("Cancelled")
                || a.getStatus().equalsIgnoreCase("Completed")) {
            continue;
        }

        if (upcoming == null ||
                LocalDate.parse(a.getDate())
                        .isAfter(LocalDate.parse(upcoming.getDate()))) {

            upcoming = a;
        }
    }

    // Display appointment
    if (upcoming != null) {
        dateValueLbl.setText(upcoming.getDate());
        timeValueLbl.setText(upcoming.getTime());
        counselorValueLbl.setText(upcoming.getCounselorUsername());
        statusValueLbl.setText(upcoming.getStatus());
    } else {
        dateValueLbl.setText("No Appointment");
        timeValueLbl.setText("-");
        counselorValueLbl.setText("-");
        statusValueLbl.setText("-");
    }

    // Queue information
    if (student.getQueueNumber() == -1) {
        queueValueLbl.setText("No Queue");
        waitingValueLbl.setText("-");
    } else {
        queueValueLbl.setText(String.valueOf(student.getQueueNumber()));
        waitingValueLbl.setText(student.getQueueNumber() * 10 + " mins");
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel counselorValueLbl;
    private javax.swing.JLabel dateValueLbl;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel png;
    private javax.swing.JLabel queueValueLbl;
    private javax.swing.JLabel statusValueLbl;
    private javax.swing.JLabel timeValueLbl;
    private javax.swing.JLabel waitingValueLbl;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
