/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package OOPAssignment.Gui;

import OOPAssignment.model.Admin;
import OOPAssignment.model.Student;
import java.awt.CardLayout;


public class StudentPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;
    private Admin admin;
    private Student loggedInStudent;
    private CardLayout innerCardLayout;

    public StudentPanel(MainFrame mainFrame, Admin admin, Student loggedInStudent) {
        initComponents();
        
         makeTransparentButton(dashboardBtn);
         makeTransparentButton(historyBtn);
         makeTransparentButton(bookBtn);
         makeTransparentButton(profilesBtn);
         makeTransparentButton(queueBtn);
         makeTransparentButton(logoutBtn);
         
        this.mainFrame = mainFrame;
        this.admin = admin;
        this.loggedInStudent = loggedInStudent;

        innerCardLayout = new CardLayout();
        contentPanel.setLayout(innerCardLayout);

        contentPanel.add(new StudentDashboardPanel(loggedInStudent), "dashboard");
        contentPanel.add(new BookAppointmentPanel(loggedInStudent), "book");
        contentPanel.add(new MyAppointmentHistoryPanel(loggedInStudent), "history");
        contentPanel.add(new CounselorProfilesPanel(admin), "profiles");
        contentPanel.add(new QueueStatusPanel(loggedInStudent), "queue");

        innerCardLayout.show(contentPanel, "dashboard");
        
    }
    
    private void makeTransparentButton(javax.swing.JButton button) {
    button.setOpaque(false);
    button.setContentAreaFilled(false);
    button.setBorderPainted(false);
    button.setFocusPainted(false);
    button.setBorder(null);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        dashboardBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        bookBtn = new javax.swing.JButton();
        historyBtn = new javax.swing.JButton();
        profilesBtn = new javax.swing.JButton();
        queueBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOPAssignment/Gui/apulogo (1).png"))); // NOI18N

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboardBtn.setText("Dashboard");
        dashboardBtn.setMaximumSize(new java.awt.Dimension(100, 35));
        dashboardBtn.setMinimumSize(new java.awt.Dimension(100, 35));
        dashboardBtn.addActionListener(this::dashboardBtnActionPerformed);
        add(dashboardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 100, 40));

        logoutBtn.setText("log out");
        logoutBtn.addActionListener(this::logoutBtnActionPerformed);
        add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 100, 40));

        contentPanel.setLayout(new java.awt.CardLayout());
        add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(927, 0, -1, -1));

        bookBtn.setText("Book");
        bookBtn.addActionListener(this::bookBtnActionPerformed);
        add(bookBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 265, 100, 40));

        historyBtn.setText("history");
        historyBtn.setPreferredSize(new java.awt.Dimension(100, 35));
        historyBtn.addActionListener(this::historyBtnActionPerformed);
        add(historyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 100, 40));

        profilesBtn.setText("profiles");
        profilesBtn.addActionListener(this::profilesBtnActionPerformed);
        add(profilesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 100, 50));

        queueBtn.setText("Queue");
        queueBtn.addActionListener(this::queueBtnActionPerformed);
        add(queueBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 385, 100, 50));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1255, -1, 382));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 2, -1, 1639));

        jPanel1.setLayout(new java.awt.CardLayout());
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(853, 1637, 74, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOPAssignment/Gui/apulogo (1).png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOPAssignment/Gui/StudentDashboard.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-320, 0, 500, 510));
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
       mainFrame.showPanel("menu");
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
        innerCardLayout.show(contentPanel, "dashboard");
    }//GEN-LAST:event_dashboardBtnActionPerformed

    private void queueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queueBtnActionPerformed
        innerCardLayout.show(contentPanel, "queue");
    }//GEN-LAST:event_queueBtnActionPerformed

    private void bookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookBtnActionPerformed
        innerCardLayout.show(contentPanel, "book");
    }//GEN-LAST:event_bookBtnActionPerformed

    private void historyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyBtnActionPerformed
        innerCardLayout.show(contentPanel, "history");
    }//GEN-LAST:event_historyBtnActionPerformed

    private void profilesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilesBtnActionPerformed
        innerCardLayout.show(contentPanel, "profiles");
    }//GEN-LAST:event_profilesBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookBtn;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton dashboardBtn;
    private javax.swing.JButton historyBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton profilesBtn;
    private javax.swing.JButton queueBtn;
    // End of variables declaration//GEN-END:variables
}
