/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package OOPAssignment.Gui;

import OOPAssignment.model.Student;

public class StudentLoginPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;

    public StudentLoginPanel(MainFrame mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;

        usernameTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    passwordTf.requestFocus();
                }
            }
        });

        passwordTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    loginBtnActionPerformed(null);
                }
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane();
        backBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        usernameTf = new javax.swing.JTextField();
        passwordTf = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        backBtn.setText("Back");
        backBtn.addActionListener(this::backBtnActionPerformed);

        jLayeredPane2.setLayer(backBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addComponent(backBtn)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addComponent(backBtn)
                .addGap(0, 77, Short.MAX_VALUE))
        );

        add(jLayeredPane2);
        jLayeredPane2.setBounds(463, 332, 155, 100);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOPAssignment/Gui/apulogo (1).png"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(0, 0, 110, 100);

        jLabel2.setText("Username:");
        add(jLabel2);
        jLabel2.setBounds(270, 170, 56, 16);

        jLabel3.setText("Password:");
        add(jLabel3);
        jLabel3.setBounds(260, 240, 53, 16);

        loginBtn.setText("Login");
        loginBtn.addActionListener(this::loginBtnActionPerformed);
        add(loginBtn);
        loginBtn.setBounds(300, 320, 72, 23);

        usernameTf.addActionListener(this::usernameTfActionPerformed);
        add(usernameTf);
        usernameTf.setBounds(400, 160, 171, 22);

        passwordTf.addActionListener(this::passwordTfActionPerformed);
        add(passwordTf);
        passwordTf.setBounds(400, 240, 171, 22);

        jLabel1.setText("Student Login");
        add(jLabel1);
        jLabel1.setBounds(390, 60, 74, 16);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTfActionPerformed

    private void passwordTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTfActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        String inputUsername = usernameTf.getText();
        String inputPassword = passwordTf.getText();

        Student student = new Student();
        boolean success = student.login(inputUsername, inputPassword);

        if (success) {
            javax.swing.JOptionPane.showMessageDialog(this, "Login successful!");
            mainFrame.showStudentPanel(student);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Wrong username or password!");
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        mainFrame.showPanel("menu");
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passwordTf;
    private javax.swing.JTextField usernameTf;
    // End of variables declaration//GEN-END:variables
}
